// Generated by Sterling SDK Generator
// Orchestrator Control Plane API v0.1.0

package sh.vers.sdk;

import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;

import java.io.IOException;
import java.net.URI;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;
import java.time.Duration;
import java.time.Instant;
import java.time.format.DateTimeFormatter;
import java.time.format.DateTimeParseException;
import java.util.Map;
import java.util.UUID;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 * Client for Orchestrator Control Plane API.
 *
 * <p>Provides typed methods for every API operation with automatic retries,
 * exponential backoff, idempotency keys, and Bearer token auth.</p>
 */
public class VersClient implements AutoCloseable {

    private static final Logger logger = Logger.getLogger("sh.vers.sdk");

    private final String baseUrl;
    private final String apiKey;
    private final int maxRetries;
    private final Duration timeout;
    private final HttpClient httpClient;
    private final ObjectMapper objectMapper;
    private final String userAgent;

    private static final int[] RETRYABLE_STATUS_CODES = {408, 409, 429};

    /**
     * Create a new VersClient with the given options.
     *
     * @param baseUrl     Base URL for the API (defaults to VERS_BASE_URL env or https://api.vers.sh)
     * @param apiKey      Bearer token (defaults to VERS_API_KEY env)
     * @param maxRetries  Maximum number of retries (default 2)
     * @param timeout     Request timeout (default 30s)
     * @param httpClient  Optional pre-configured HttpClient
     */
    public VersClient(String baseUrl, String apiKey, int maxRetries, Duration timeout, HttpClient httpClient) {
        this.baseUrl = baseUrl != null ? baseUrl : envOrDefault("VERS_BASE_URL", "https://api.vers.sh");
        this.apiKey = apiKey != null ? apiKey : System.getenv("VERS_API_KEY");
        this.maxRetries = maxRetries;
        this.timeout = timeout;
        this.httpClient = httpClient != null ? httpClient : HttpClient.newBuilder()
                .connectTimeout(timeout)
                .build();
        this.objectMapper = new ObjectMapper();
        this.userAgent = "vers-sdk/0.1.8 java/" + System.getProperty("java.version")
                + " " + System.getProperty("os.name").toLowerCase() + "/" + System.getProperty("os.arch");
    }

    /** Create a client with defaults. */
    public VersClient() {
        this(null, null, 2, Duration.ofSeconds(30), null);
    }

    /** Create a client with base URL and API key. */
    public VersClient(String baseUrl, String apiKey) {
        this(baseUrl, apiKey, 2, Duration.ofSeconds(30), null);
    }

    // ── Operations ──────────────────────────────────────────────────────

    /**
     * 
     */
    public Map<String, Object> vmStatus(String vm_id, RequestOptions options) throws IOException, InterruptedException {
        String path = String.format("/api/v1/vm/%s/status", vm_id);
        HttpResponse<String> response = doRequest("GET", path, null, options);
        return objectMapper.readValue(response.body(), new TypeReference<Map<String, Object>>() {});
    }

    /**
     * 
     */
    public Map<String, Object> resizeVmDisk(String vm_id, Map<String, Object> body, Models.ResizeVmDiskParams params, RequestOptions options) throws IOException, InterruptedException {
        String path = String.format("/api/v1/vm/%s/disk", vm_id);
        StringBuilder query = new StringBuilder();
        if (params != null) {
            if (params.skip_wait_boot != null) {
                query.append(query.length() == 0 ? "?" : "&");
                query.append("skip_wait_boot=").append(params.skip_wait_boot);
            }
        }
        path = path + query.toString();
        HttpResponse<String> response = doRequest("PATCH", path, body, options);
        return objectMapper.readValue(response.body(), new TypeReference<Map<String, Object>>() {});
    }

    /**
     * 
     */
    public Map<String, Object> execVmStreamAttach(String vm_id, Map<String, Object> body, RequestOptions options) throws IOException, InterruptedException {
        String path = String.format("/api/v1/vm/%s/exec/stream/attach", vm_id);
        HttpResponse<String> response = doRequest("POST", path, body, options);
        return objectMapper.readValue(response.body(), new TypeReference<Map<String, Object>>() {});
    }

    /**
     * 
     */
    public Map<String, Object> listVms(RequestOptions options) throws IOException, InterruptedException {
        String path = "/api/v1/vms";
        HttpResponse<String> response = doRequest("GET", path, null, options);
        return objectMapper.readValue(response.body(), new TypeReference<Map<String, Object>>() {});
    }

    /**
     * 
     */
    public Map<String, Object> createNewRootVm(Map<String, Object> body, Models.CreateNewRootVmParams params, RequestOptions options) throws IOException, InterruptedException {
        String path = "/api/v1/vm/new_root";
        StringBuilder query = new StringBuilder();
        if (params != null) {
            if (params.wait_boot != null) {
                query.append(query.length() == 0 ? "?" : "&");
                query.append("wait_boot=").append(params.wait_boot);
            }
        }
        path = path + query.toString();
        HttpResponse<String> response = doRequest("POST", path, body, options);
        return objectMapper.readValue(response.body(), new TypeReference<Map<String, Object>>() {});
    }

    /**
     * 
     */
    public Map<String, Object> vmLogs(String vm_id, Models.VmLogsParams params, RequestOptions options) throws IOException, InterruptedException {
        String path = String.format("/api/v1/vm/%s/logs", vm_id);
        StringBuilder query = new StringBuilder();
        if (params != null) {
            if (params.offset != null) {
                query.append(query.length() == 0 ? "?" : "&");
                query.append("offset=").append(params.offset);
            }
            if (params.max_entries != null) {
                query.append(query.length() == 0 ? "?" : "&");
                query.append("max_entries=").append(params.max_entries);
            }
            if (params.stream != null) {
                query.append(query.length() == 0 ? "?" : "&");
                query.append("stream=").append(params.stream);
            }
        }
        path = path + query.toString();
        HttpResponse<String> response = doRequest("GET", path, null, options);
        return objectMapper.readValue(response.body(), new TypeReference<Map<String, Object>>() {});
    }

    /**
     * 
     */
    public Map<String, Object> branchByRef(String repo_name, String tag_name, Map<String, Object> body, Models.BranchByRefParams params, RequestOptions options) throws IOException, InterruptedException {
        String path = String.format("/api/v1/vm/branch/by_ref/%s/%s", repo_name, tag_name);
        StringBuilder query = new StringBuilder();
        if (params != null) {
            if (params.count != null) {
                query.append(query.length() == 0 ? "?" : "&");
                query.append("count=").append(params.count);
            }
        }
        path = path + query.toString();
        HttpResponse<String> response = doRequest("POST", path, body, options);
        return objectMapper.readValue(response.body(), new TypeReference<Map<String, Object>>() {});
    }

    /**
     * 
     */
    public Map<String, Object> labelVm(String vm_id, Map<String, Object> body, RequestOptions options) throws IOException, InterruptedException {
        String path = String.format("/api/v1/vm/%s/label", vm_id);
        HttpResponse<String> response = doRequest("PATCH", path, body, options);
        return objectMapper.readValue(response.body(), new TypeReference<Map<String, Object>>() {});
    }

    /**
     * 
     */
    public Map<String, Object> listPublicCommits(RequestOptions options) throws IOException, InterruptedException {
        String path = "/api/v1/commits/public";
        HttpResponse<String> response = doRequest("GET", path, null, options);
        return objectMapper.readValue(response.body(), new TypeReference<Map<String, Object>>() {});
    }

    /**
     * 
     */
    public Map<String, Object> getImageStatus(String image_name, RequestOptions options) throws IOException, InterruptedException {
        String path = String.format("/api/v1/images/%s/status", image_name);
        HttpResponse<String> response = doRequest("GET", path, null, options);
        return objectMapper.readValue(response.body(), new TypeReference<Map<String, Object>>() {});
    }

    /**
     * 
     */
    public Map<String, Object> listPublicRepoTags(String org_name, String repo_name, RequestOptions options) throws IOException, InterruptedException {
        String path = String.format("/api/v1/public/repositories/%s/%s/tags", org_name, repo_name);
        HttpResponse<String> response = doRequest("GET", path, null, options);
        return objectMapper.readValue(response.body(), new TypeReference<Map<String, Object>>() {});
    }

    /**
     * 
     */
    public Map<String, Object> versionHandler(RequestOptions options) throws IOException, InterruptedException {
        String path = "/api/v1/system/version";
        HttpResponse<String> response = doRequest("GET", path, null, options);
        return objectMapper.readValue(response.body(), new TypeReference<Map<String, Object>>() {});
    }

    /**
     * 
     */
    public Map<String, Object> branchByTag(String tag_name, Map<String, Object> body, Models.BranchByTagParams params, RequestOptions options) throws IOException, InterruptedException {
        String path = String.format("/api/v1/vm/branch/by_tag/%s", tag_name);
        StringBuilder query = new StringBuilder();
        if (params != null) {
            if (params.count != null) {
                query.append(query.length() == 0 ? "?" : "&");
                query.append("count=").append(params.count);
            }
        }
        path = path + query.toString();
        HttpResponse<String> response = doRequest("POST", path, body, options);
        return objectMapper.readValue(response.body(), new TypeReference<Map<String, Object>>() {});
    }

    /**
     * 
     */
    public Map<String, Object> getRepoTag(String repo_name, String tag_name, RequestOptions options) throws IOException, InterruptedException {
        String path = String.format("/api/v1/repositories/%s/tags/%s", repo_name, tag_name);
        HttpResponse<String> response = doRequest("GET", path, null, options);
        return objectMapper.readValue(response.body(), new TypeReference<Map<String, Object>>() {});
    }

    /**
     * 
     */
    public Map<String, Object> deleteRepoTag(String repo_name, String tag_name, RequestOptions options) throws IOException, InterruptedException {
        String path = String.format("/api/v1/repositories/%s/tags/%s", repo_name, tag_name);
        HttpResponse<String> response = doRequest("DELETE", path, null, options);
        return objectMapper.readValue(response.body(), new TypeReference<Map<String, Object>>() {});
    }

    /**
     * 
     */
    public Map<String, Object> updateRepoTag(String repo_name, String tag_name, Map<String, Object> body, RequestOptions options) throws IOException, InterruptedException {
        String path = String.format("/api/v1/repositories/%s/tags/%s", repo_name, tag_name);
        HttpResponse<String> response = doRequest("PATCH", path, body, options);
        return objectMapper.readValue(response.body(), new TypeReference<Map<String, Object>>() {});
    }

    /**
     * 
     */
    public Map<String, Object> branchVm(String vm_or_commit_id, Map<String, Object> body, Models.BranchVmParams params, RequestOptions options) throws IOException, InterruptedException {
        String path = String.format("/api/v1/vm/%s/branch", vm_or_commit_id);
        StringBuilder query = new StringBuilder();
        if (params != null) {
            if (params.keep_paused != null) {
                query.append(query.length() == 0 ? "?" : "&");
                query.append("keep_paused=").append(params.keep_paused);
            }
            if (params.skip_wait_boot != null) {
                query.append(query.length() == 0 ? "?" : "&");
                query.append("skip_wait_boot=").append(params.skip_wait_boot);
            }
            if (params.count != null) {
                query.append(query.length() == 0 ? "?" : "&");
                query.append("count=").append(params.count);
            }
        }
        path = path + query.toString();
        HttpResponse<String> response = doRequest("POST", path, body, options);
        return objectMapper.readValue(response.body(), new TypeReference<Map<String, Object>>() {});
    }

    /**
     * 
     */
    public Map<String, Object> getRepository(String repo_name, RequestOptions options) throws IOException, InterruptedException {
        String path = String.format("/api/v1/repositories/%s", repo_name);
        HttpResponse<String> response = doRequest("GET", path, null, options);
        return objectMapper.readValue(response.body(), new TypeReference<Map<String, Object>>() {});
    }

    /**
     * 
     */
    public Map<String, Object> deleteRepository(String repo_name, RequestOptions options) throws IOException, InterruptedException {
        String path = String.format("/api/v1/repositories/%s", repo_name);
        HttpResponse<String> response = doRequest("DELETE", path, null, options);
        return objectMapper.readValue(response.body(), new TypeReference<Map<String, Object>>() {});
    }

    /**
     * 
     */
    public Map<String, Object> listParentCommits(String commit_id, RequestOptions options) throws IOException, InterruptedException {
        String path = String.format("/api/v1/vm/commits/%s/parents", commit_id);
        HttpResponse<String> response = doRequest("GET", path, null, options);
        return objectMapper.readValue(response.body(), new TypeReference<Map<String, Object>>() {});
    }

    /**
     * 
     */
    public Map<String, Object> validateKey(Map<String, Object> body, RequestOptions options) throws IOException, InterruptedException {
        String path = "/api/v1/keys/validate";
        HttpResponse<String> response = doRequest("POST", path, body, options);
        return objectMapper.readValue(response.body(), new TypeReference<Map<String, Object>>() {});
    }

    /**
     * 
     */
    public Map<String, Object> forkRepository(Map<String, Object> body, RequestOptions options) throws IOException, InterruptedException {
        String path = "/api/v1/repositories/fork";
        HttpResponse<String> response = doRequest("POST", path, body, options);
        return objectMapper.readValue(response.body(), new TypeReference<Map<String, Object>>() {});
    }

    /**
     * 
     */
    public Map<String, Object> listRepositories(RequestOptions options) throws IOException, InterruptedException {
        String path = "/api/v1/repositories";
        HttpResponse<String> response = doRequest("GET", path, null, options);
        return objectMapper.readValue(response.body(), new TypeReference<Map<String, Object>>() {});
    }

    /**
     * 
     */
    public Map<String, Object> createRepository(Map<String, Object> body, RequestOptions options) throws IOException, InterruptedException {
        String path = "/api/v1/repositories";
        HttpResponse<String> response = doRequest("POST", path, body, options);
        return objectMapper.readValue(response.body(), new TypeReference<Map<String, Object>>() {});
    }

    /**
     * 
     */
    public Map<String, Object> updateVmState(String vm_id, Map<String, Object> body, Models.UpdateVmStateParams params, RequestOptions options) throws IOException, InterruptedException {
        String path = String.format("/api/v1/vm/%s/state", vm_id);
        StringBuilder query = new StringBuilder();
        if (params != null) {
            if (params.skip_wait_boot != null) {
                query.append(query.length() == 0 ? "?" : "&");
                query.append("skip_wait_boot=").append(params.skip_wait_boot);
            }
        }
        path = path + query.toString();
        HttpResponse<String> response = doRequest("PATCH", path, body, options);
        return objectMapper.readValue(response.body(), new TypeReference<Map<String, Object>>() {});
    }

    /**
     * 
     */
    public Map<String, Object> createImage(Map<String, Object> body, RequestOptions options) throws IOException, InterruptedException {
        String path = "/api/v1/images/create";
        HttpResponse<String> response = doRequest("POST", path, body, options);
        return objectMapper.readValue(response.body(), new TypeReference<Map<String, Object>>() {});
    }

    /**
     * 
     */
    public Map<String, Object> restoreFromCommit(Map<String, Object> body, RequestOptions options) throws IOException, InterruptedException {
        String path = "/api/v1/vm/from_commit";
        HttpResponse<String> response = doRequest("POST", path, body, options);
        return objectMapper.readValue(response.body(), new TypeReference<Map<String, Object>>() {});
    }

    /**
     * 
     */
    public Map<String, Object> getDomain(String domain_id, RequestOptions options) throws IOException, InterruptedException {
        String path = String.format("/api/v1/domains/%s", domain_id);
        HttpResponse<String> response = doRequest("GET", path, null, options);
        return objectMapper.readValue(response.body(), new TypeReference<Map<String, Object>>() {});
    }

    /**
     * 
     */
    public Map<String, Object> deleteDomain(String domain_id, RequestOptions options) throws IOException, InterruptedException {
        String path = String.format("/api/v1/domains/%s", domain_id);
        HttpResponse<String> response = doRequest("DELETE", path, null, options);
        return objectMapper.readValue(response.body(), new TypeReference<Map<String, Object>>() {});
    }

    /**
     * 
     */
    public Map<String, Object> listTags(RequestOptions options) throws IOException, InterruptedException {
        String path = "/api/v1/commit_tags";
        HttpResponse<String> response = doRequest("GET", path, null, options);
        return objectMapper.readValue(response.body(), new TypeReference<Map<String, Object>>() {});
    }

    /**
     * 
     */
    public Map<String, Object> createTag(Map<String, Object> body, RequestOptions options) throws IOException, InterruptedException {
        String path = "/api/v1/commit_tags";
        HttpResponse<String> response = doRequest("POST", path, body, options);
        return objectMapper.readValue(response.body(), new TypeReference<Map<String, Object>>() {});
    }

    /**
     * 
     */
    public Map<String, Object> listPublicRepositories(RequestOptions options) throws IOException, InterruptedException {
        String path = "/api/v1/public/repositories";
        HttpResponse<String> response = doRequest("GET", path, null, options);
        return objectMapper.readValue(response.body(), new TypeReference<Map<String, Object>>() {});
    }

    /**
     * 
     */
    public Map<String, Object> getPublicRepoTag(String org_name, String repo_name, String tag_name, RequestOptions options) throws IOException, InterruptedException {
        String path = String.format("/api/v1/public/repositories/%s/%s/tags/%s", org_name, repo_name, tag_name);
        HttpResponse<String> response = doRequest("GET", path, null, options);
        return objectMapper.readValue(response.body(), new TypeReference<Map<String, Object>>() {});
    }

    /**
     * 
     */
    public Map<String, Object> getVmMetadata(String vm_id, RequestOptions options) throws IOException, InterruptedException {
        String path = String.format("/api/v1/vm/%s/metadata", vm_id);
        HttpResponse<String> response = doRequest("GET", path, null, options);
        return objectMapper.readValue(response.body(), new TypeReference<Map<String, Object>>() {});
    }

    /**
     * 
     */
    public Map<String, Object> listEnvVars(RequestOptions options) throws IOException, InterruptedException {
        String path = "/api/v1/env_vars";
        HttpResponse<String> response = doRequest("GET", path, null, options);
        return objectMapper.readValue(response.body(), new TypeReference<Map<String, Object>>() {});
    }

    /**
     * 
     */
    public Map<String, Object> setEnvVars(Map<String, Object> body, RequestOptions options) throws IOException, InterruptedException {
        String path = "/api/v1/env_vars";
        HttpResponse<String> response = doRequest("PUT", path, body, options);
        return objectMapper.readValue(response.body(), new TypeReference<Map<String, Object>>() {});
    }

    /**
     * 
     */
    public Map<String, Object> deleteVm(String vm_id, Models.DeleteVmParams params, RequestOptions options) throws IOException, InterruptedException {
        String path = String.format("/api/v1/vm/%s", vm_id);
        StringBuilder query = new StringBuilder();
        if (params != null) {
            if (params.skip_wait_boot != null) {
                query.append(query.length() == 0 ? "?" : "&");
                query.append("skip_wait_boot=").append(params.skip_wait_boot);
            }
        }
        path = path + query.toString();
        HttpResponse<String> response = doRequest("DELETE", path, null, options);
        return objectMapper.readValue(response.body(), new TypeReference<Map<String, Object>>() {});
    }

    /**
     * 
     */
    public Map<String, Object> listCommits(RequestOptions options) throws IOException, InterruptedException {
        String path = "/api/v1/commits";
        HttpResponse<String> response = doRequest("GET", path, null, options);
        return objectMapper.readValue(response.body(), new TypeReference<Map<String, Object>>() {});
    }

    /**
     * 
     */
    public Map<String, Object> getTag(String tag_name, RequestOptions options) throws IOException, InterruptedException {
        String path = String.format("/api/v1/commit_tags/%s", tag_name);
        HttpResponse<String> response = doRequest("GET", path, null, options);
        return objectMapper.readValue(response.body(), new TypeReference<Map<String, Object>>() {});
    }

    /**
     * 
     */
    public Map<String, Object> deleteTag(String tag_name, RequestOptions options) throws IOException, InterruptedException {
        String path = String.format("/api/v1/commit_tags/%s", tag_name);
        HttpResponse<String> response = doRequest("DELETE", path, null, options);
        return objectMapper.readValue(response.body(), new TypeReference<Map<String, Object>>() {});
    }

    /**
     * 
     */
    public Map<String, Object> updateTag(String tag_name, Map<String, Object> body, RequestOptions options) throws IOException, InterruptedException {
        String path = String.format("/api/v1/commit_tags/%s", tag_name);
        HttpResponse<String> response = doRequest("PATCH", path, body, options);
        return objectMapper.readValue(response.body(), new TypeReference<Map<String, Object>>() {});
    }

    /**
     * 
     */
    public Map<String, Object> branchByVm(String vm_id, Map<String, Object> body, Models.BranchByVmParams params, RequestOptions options) throws IOException, InterruptedException {
        String path = String.format("/api/v1/vm/branch/by_vm/%s", vm_id);
        StringBuilder query = new StringBuilder();
        if (params != null) {
            if (params.keep_paused != null) {
                query.append(query.length() == 0 ? "?" : "&");
                query.append("keep_paused=").append(params.keep_paused);
            }
            if (params.skip_wait_boot != null) {
                query.append(query.length() == 0 ? "?" : "&");
                query.append("skip_wait_boot=").append(params.skip_wait_boot);
            }
            if (params.count != null) {
                query.append(query.length() == 0 ? "?" : "&");
                query.append("count=").append(params.count);
            }
        }
        path = path + query.toString();
        HttpResponse<String> response = doRequest("POST", path, body, options);
        return objectMapper.readValue(response.body(), new TypeReference<Map<String, Object>>() {});
    }

    /**
     * 
     */
    public Map<String, Object> deleteEnvVar(String key, RequestOptions options) throws IOException, InterruptedException {
        String path = String.format("/api/v1/env_vars/%s", key);
        HttpResponse<String> response = doRequest("DELETE", path, null, options);
        return objectMapper.readValue(response.body(), new TypeReference<Map<String, Object>>() {});
    }

    /**
     * 
     */
    public Map<String, Object> deleteImage(String base_image_id, RequestOptions options) throws IOException, InterruptedException {
        String path = String.format("/api/v1/images/images/%s", base_image_id);
        HttpResponse<String> response = doRequest("DELETE", path, null, options);
        return objectMapper.readValue(response.body(), new TypeReference<Map<String, Object>>() {});
    }

    /**
     * 
     */
    public Map<String, Object> commitVm(String vm_id, Map<String, Object> body, Models.CommitVmParams params, RequestOptions options) throws IOException, InterruptedException {
        String path = String.format("/api/v1/vm/%s/commit", vm_id);
        StringBuilder query = new StringBuilder();
        if (params != null) {
            if (params.keep_paused != null) {
                query.append(query.length() == 0 ? "?" : "&");
                query.append("keep_paused=").append(params.keep_paused);
            }
            if (params.skip_wait_boot != null) {
                query.append(query.length() == 0 ? "?" : "&");
                query.append("skip_wait_boot=").append(params.skip_wait_boot);
            }
        }
        path = path + query.toString();
        HttpResponse<String> response = doRequest("POST", path, body, options);
        return objectMapper.readValue(response.body(), new TypeReference<Map<String, Object>>() {});
    }

    /**
     * 
     */
    public Map<String, Object> deleteCommit(String commit_id, RequestOptions options) throws IOException, InterruptedException {
        String path = String.format("/api/v1/commits/%s", commit_id);
        HttpResponse<String> response = doRequest("DELETE", path, null, options);
        return objectMapper.readValue(response.body(), new TypeReference<Map<String, Object>>() {});
    }

    /**
     * 
     */
    public Map<String, Object> updateCommit(String commit_id, Map<String, Object> body, RequestOptions options) throws IOException, InterruptedException {
        String path = String.format("/api/v1/commits/%s", commit_id);
        HttpResponse<String> response = doRequest("PATCH", path, body, options);
        return objectMapper.readValue(response.body(), new TypeReference<Map<String, Object>>() {});
    }

    /**
     * 
     */
    public Map<String, Object> listRepoTags(String repo_name, RequestOptions options) throws IOException, InterruptedException {
        String path = String.format("/api/v1/repositories/%s/tags", repo_name);
        HttpResponse<String> response = doRequest("GET", path, null, options);
        return objectMapper.readValue(response.body(), new TypeReference<Map<String, Object>>() {});
    }

    /**
     * 
     */
    public Map<String, Object> createRepoTag(String repo_name, Map<String, Object> body, RequestOptions options) throws IOException, InterruptedException {
        String path = String.format("/api/v1/repositories/%s/tags", repo_name);
        HttpResponse<String> response = doRequest("POST", path, body, options);
        return objectMapper.readValue(response.body(), new TypeReference<Map<String, Object>>() {});
    }

    /**
     * Deploy a GitHub repository to a new Vers project.
     */
    public Map<String, Object> deployHandler(Map<String, Object> body, RequestOptions options) throws IOException, InterruptedException {
        String path = "/api/v1/deploy";
        HttpResponse<String> response = doRequest("POST", path, body, options);
        return objectMapper.readValue(response.body(), new TypeReference<Map<String, Object>>() {});
    }

    /**
     * 
     */
    public Map<String, Object> execVm(String vm_id, Map<String, Object> body, RequestOptions options) throws IOException, InterruptedException {
        String path = String.format("/api/v1/vm/%s/exec", vm_id);
        HttpResponse<String> response = doRequest("POST", path, body, options);
        return objectMapper.readValue(response.body(), new TypeReference<Map<String, Object>>() {});
    }

    /**
     * 
     */
    public Map<String, Object> setRepositoryVisibility(String repo_name, Map<String, Object> body, RequestOptions options) throws IOException, InterruptedException {
        String path = String.format("/api/v1/repositories/%s/visibility", repo_name);
        HttpResponse<String> response = doRequest("PATCH", path, body, options);
        return objectMapper.readValue(response.body(), new TypeReference<Map<String, Object>>() {});
    }

    /**
     * 
     */
    public Map<String, Object> execVmStream(String vm_id, Map<String, Object> body, RequestOptions options) throws IOException, InterruptedException {
        String path = String.format("/api/v1/vm/%s/exec/stream", vm_id);
        HttpResponse<String> response = doRequest("POST", path, body, options);
        return objectMapper.readValue(response.body(), new TypeReference<Map<String, Object>>() {});
    }

    /**
     * 
     */
    public Map<String, Object> listDomains(Models.ListDomainsParams params, RequestOptions options) throws IOException, InterruptedException {
        String path = "/api/v1/domains";
        StringBuilder query = new StringBuilder();
        if (params != null) {
            if (params.vm_id != null) {
                query.append(query.length() == 0 ? "?" : "&");
                query.append("vm_id=").append(params.vm_id);
            }
        }
        path = path + query.toString();
        HttpResponse<String> response = doRequest("GET", path, null, options);
        return objectMapper.readValue(response.body(), new TypeReference<Map<String, Object>>() {});
    }

    /**
     * 
     */
    public Map<String, Object> createDomain(Map<String, Object> body, RequestOptions options) throws IOException, InterruptedException {
        String path = "/api/v1/domains";
        HttpResponse<String> response = doRequest("POST", path, body, options);
        return objectMapper.readValue(response.body(), new TypeReference<Map<String, Object>>() {});
    }

    /**
     * 
     */
    public Map<String, Object> sshKey(String vm_id, RequestOptions options) throws IOException, InterruptedException {
        String path = String.format("/api/v1/vm/%s/ssh_key", vm_id);
        HttpResponse<String> response = doRequest("GET", path, null, options);
        return objectMapper.readValue(response.body(), new TypeReference<Map<String, Object>>() {});
    }

    /**
     * 
     */
    public Map<String, Object> listImages(RequestOptions options) throws IOException, InterruptedException {
        String path = "/api/v1/images";
        HttpResponse<String> response = doRequest("GET", path, null, options);
        return objectMapper.readValue(response.body(), new TypeReference<Map<String, Object>>() {});
    }

    /**
     * 
     */
    public Map<String, Object> readFileVm(String vm_id, Models.ReadFileVmParams params, RequestOptions options) throws IOException, InterruptedException {
        String path = String.format("/api/v1/vm/%s/files", vm_id);
        StringBuilder query = new StringBuilder();
        if (params != null) {
            if (params.path != null) {
                query.append(query.length() == 0 ? "?" : "&");
                query.append("path=").append(params.path);
            }
        }
        path = path + query.toString();
        HttpResponse<String> response = doRequest("GET", path, null, options);
        return objectMapper.readValue(response.body(), new TypeReference<Map<String, Object>>() {});
    }

    /**
     * 
     */
    public Map<String, Object> writeFileVm(String vm_id, Map<String, Object> body, RequestOptions options) throws IOException, InterruptedException {
        String path = String.format("/api/v1/vm/%s/files", vm_id);
        HttpResponse<String> response = doRequest("PUT", path, body, options);
        return objectMapper.readValue(response.body(), new TypeReference<Map<String, Object>>() {});
    }

    /**
     * 
     */
    public Map<String, Object> uploadImage(Map<String, Object> body, RequestOptions options) throws IOException, InterruptedException {
        String path = "/api/v1/images/upload";
        HttpResponse<String> response = doRequest("POST", path, body, options);
        return objectMapper.readValue(response.body(), new TypeReference<Map<String, Object>>() {});
    }

    /**
     * 
     */
    public Map<String, Object> getPublicRepository(String org_name, String repo_name, RequestOptions options) throws IOException, InterruptedException {
        String path = String.format("/api/v1/public/repositories/%s/%s", org_name, repo_name);
        HttpResponse<String> response = doRequest("GET", path, null, options);
        return objectMapper.readValue(response.body(), new TypeReference<Map<String, Object>>() {});
    }

    /**
     * 
     */
    public Map<String, Object> branchByCommit(String commit_id, Map<String, Object> body, Models.BranchByCommitParams params, RequestOptions options) throws IOException, InterruptedException {
        String path = String.format("/api/v1/vm/branch/by_commit/%s", commit_id);
        StringBuilder query = new StringBuilder();
        if (params != null) {
            if (params.count != null) {
                query.append(query.length() == 0 ? "?" : "&");
                query.append("count=").append(params.count);
            }
        }
        path = path + query.toString();
        HttpResponse<String> response = doRequest("POST", path, body, options);
        return objectMapper.readValue(response.body(), new TypeReference<Map<String, Object>>() {});
    }

    // ── Internal ────────────────────────────────────────────────────────

    private HttpResponse<String> doRequest(String method, String path, Object body, RequestOptions options)
            throws IOException, InterruptedException {
        logger.fine(() -> "request: " + method + " " + path);

        Duration effectiveTimeout = (options != null && options.getTimeout() != null) ? options.getTimeout() : this.timeout;

        IOException lastException = null;
        boolean retryAfterUsed = false;

        for (int attempt = 0; attempt <= maxRetries; attempt++) {
            if (attempt > 0 && !retryAfterUsed) {
                long delay = retryDelay(attempt - 1);
                final int attemptNum = attempt;
                logger.info(() -> "retry attempt " + attemptNum + "/" + maxRetries + " for " + method + " " + path);
                Thread.sleep(delay);
            }
            retryAfterUsed = false;

            try {
                String url = baseUrl + path;
                HttpRequest.Builder reqBuilder = HttpRequest.newBuilder()
                        .uri(URI.create(url))
                        .timeout(effectiveTimeout)
                        .header("User-Agent", userAgent)
                        .header("Content-Type", "application/json")
                        .header("Accept", "application/json");

                if (apiKey != null && !apiKey.isEmpty()) {
                    reqBuilder.header("Authorization", "Bearer " + apiKey);
                }

                // Idempotency key for mutating methods
                if ("POST".equals(method) || "PUT".equals(method) || "PATCH".equals(method) || "DELETE".equals(method)) {
                    reqBuilder.header("X-Idempotency-Key", UUID.randomUUID().toString());
                }

                // Per-request header overrides
                if (options != null && options.getHeaders() != null) {
                    for (Map.Entry<String, String> entry : options.getHeaders().entrySet()) {
                        reqBuilder.header(entry.getKey(), entry.getValue());
                    }
                }

                // Set method and body
                HttpRequest.BodyPublisher bodyPublisher = (body != null)
                        ? HttpRequest.BodyPublishers.ofString(objectMapper.writeValueAsString(body))
                        : HttpRequest.BodyPublishers.noBody();

                reqBuilder.method(method, bodyPublisher);

                HttpRequest request = reqBuilder.build();
                HttpResponse<String> response = httpClient.send(request, HttpResponse.BodyHandlers.ofString());

                logger.fine(() -> "response: " + response.statusCode() + " for " + method + " " + path);

                if (isRetryableStatus(response.statusCode()) && attempt < maxRetries) {
                    Long retryAfterDelay = parseRetryAfter(response.headers().firstValue("retry-after").orElse(null));
                    if (retryAfterDelay != null) {
                        retryAfterUsed = true;
                        logger.info(() -> "retry-after: " + retryAfterDelay + "ms");
                        Thread.sleep(retryAfterDelay);
                    }
                    lastException = new IOException("HTTP " + response.statusCode());
                    continue;
                }

                checkResponse(response);
                return response;

            } catch (Errors.APIError e) {
                throw e;
            } catch (IOException e) {
                logger.warning(() -> "connection error: " + method + " " + path + " - " + e.getMessage());
                if (attempt == maxRetries) {
                    throw new Errors.APIConnectionError(e.getMessage(), e);
                }
                lastException = e;
            }
        }
        throw lastException != null ? lastException : new IOException("Request failed");
    }

    private void checkResponse(HttpResponse<String> response) throws Errors.APIError {
        int status = response.statusCode();
        if (status >= 200 && status < 300) {
            return;
        }
        Object body = null;
        String message = null;
        String contentType = response.headers().firstValue("content-type").orElse("");
        if (contentType.contains("application/json")) {
            try {
                body = objectMapper.readValue(response.body(), new TypeReference<Map<String, Object>>() {});
            } catch (Exception e) {
                message = response.body();
            }
        } else {
            message = response.body();
        }
        Map<String, String> headers = new java.util.HashMap<>();
        response.headers().map().forEach((k, v) -> {
            if (!v.isEmpty()) headers.put(k, v.get(0));
        });
        throw Errors.APIError.generate(status, body, message, headers);
    }

    private static boolean isRetryableStatus(int status) {
        if (status >= 500) return true;
        for (int code : RETRYABLE_STATUS_CODES) {
            if (code == status) return true;
        }
        return false;
    }

    private static long retryDelay(int attempt) {
        double base = 500.0 * Math.pow(2, attempt);
        double jitter = Math.random() * base * 0.25;
        return (long) (base + jitter);
    }

    private static Long parseRetryAfter(String headerValue) {
        if (headerValue == null) return null;
        try {
            double seconds = Double.parseDouble(headerValue);
            long ms = (long) (Math.min(Math.max(seconds, 0), 60) * 1000);
            return ms;
        } catch (NumberFormatException ignored) {}
        try {
            Instant parsed = Instant.from(DateTimeFormatter.RFC_1123_DATE_TIME.parse(headerValue));
            long delayMs = Duration.between(Instant.now(), parsed).toMillis();
            return Math.min(Math.max(delayMs, 0), 60000);
        } catch (DateTimeParseException ignored) {}
        return null;
    }

    private static String envOrDefault(String envKey, String defaultValue) {
        String val = System.getenv(envKey);
        return val != null ? val : defaultValue;
    }

    /** Return the underlying ObjectMapper for deserialization. */
    public ObjectMapper getObjectMapper() {
        return objectMapper;
    }

    @Override
    public void close() {
        // HttpClient does not require explicit close in Java 11
    }
}
