// Generated by Sterling SDK Generator — test suite
// Orchestrator Control Plane API v0.1.0

package com.vers.sdk;

import com.sun.net.httpserver.HttpServer;
import org.junit.jupiter.api.*;

import java.io.IOException;
import java.io.OutputStream;
import java.net.InetSocketAddress;
import java.util.Map;
import java.util.concurrent.atomic.AtomicReference;

import static org.junit.jupiter.api.Assertions.*;

/**
 * Tests for VersClient — verifies URL construction, HTTP methods, and error handling.
 */
class VersClientTest {

    // ── Test server helpers ─────────────────────────────────────────────

    static class CapturedRequest {
        String method;
        String path;
    }

    private static HttpServer startServer(int statusCode, CapturedRequest captured) throws IOException {
        HttpServer server = HttpServer.create(new InetSocketAddress(0), 0);
        server.createContext("/", exchange -> {
            captured.method = exchange.getRequestMethod();
            captured.path = exchange.getRequestURI().toString();
            String response = "{\"status\":\"ok\"}";
            exchange.getResponseHeaders().set("Content-Type", "application/json");
            exchange.sendResponseHeaders(statusCode, response.length());
            try (OutputStream os = exchange.getResponseBody()) {
                os.write(response.getBytes());
            }
        });
        server.start();
        return server;
    }

    private static VersClient makeClient(HttpServer server) {
        String baseUrl = "http://localhost:" + server.getAddress().getPort();
        return new VersClient(baseUrl, "test-key", 0, java.time.Duration.ofSeconds(5), null);
    }

    // ── Operation tests ─────────────────────────────────────────────────

    @Test
    void test_resize_vm_disk() throws Exception {
        CapturedRequest captured = new CapturedRequest();
        HttpServer server = startServer(200, captured);
        try {
            VersClient client = makeClient(server);
            client.resizeVmDisk();
            assertEquals("PATCH", captured.method, "HTTP method should be PATCH");
            assertNotNull(captured.path, "path should be captured");
            assertTrue(captured.path.startsWith("/"), "path should start with /");
        } finally {
            server.stop(0);
        }
    }

    @Test
    void test_exec_vm_stream_attach() throws Exception {
        CapturedRequest captured = new CapturedRequest();
        HttpServer server = startServer(200, captured);
        try {
            VersClient client = makeClient(server);
            client.execVmStreamAttach();
            assertEquals("POST", captured.method, "HTTP method should be POST");
            assertNotNull(captured.path, "path should be captured");
            assertTrue(captured.path.startsWith("/"), "path should start with /");
        } finally {
            server.stop(0);
        }
    }

    @Test
    void test_create_new_root_vm() throws Exception {
        CapturedRequest captured = new CapturedRequest();
        HttpServer server = startServer(200, captured);
        try {
            VersClient client = makeClient(server);
            client.createNewRootVm();
            assertEquals("POST", captured.method, "HTTP method should be POST");
            assertNotNull(captured.path, "path should be captured");
            assertTrue(captured.path.startsWith("/"), "path should start with /");
        } finally {
            server.stop(0);
        }
    }

    @Test
    void test_vm_logs() throws Exception {
        CapturedRequest captured = new CapturedRequest();
        HttpServer server = startServer(200, captured);
        try {
            VersClient client = makeClient(server);
            client.vmLogs();
            assertEquals("GET", captured.method, "HTTP method should be GET");
            assertNotNull(captured.path, "path should be captured");
            assertTrue(captured.path.startsWith("/"), "path should start with /");
        } finally {
            server.stop(0);
        }
    }

    @Test
    void test_branch_by_ref() throws Exception {
        CapturedRequest captured = new CapturedRequest();
        HttpServer server = startServer(200, captured);
        try {
            VersClient client = makeClient(server);
            client.branchByRef();
            assertEquals("POST", captured.method, "HTTP method should be POST");
            assertNotNull(captured.path, "path should be captured");
            assertTrue(captured.path.startsWith("/"), "path should start with /");
        } finally {
            server.stop(0);
        }
    }

    @Test
    void test_list_public_commits() throws Exception {
        CapturedRequest captured = new CapturedRequest();
        HttpServer server = startServer(200, captured);
        try {
            VersClient client = makeClient(server);
            client.listPublicCommits();
            assertEquals("GET", captured.method, "HTTP method should be GET");
            assertNotNull(captured.path, "path should be captured");
            assertTrue(captured.path.startsWith("/"), "path should start with /");
        } finally {
            server.stop(0);
        }
    }

    @Test
    void test_list_public_repo_tags() throws Exception {
        CapturedRequest captured = new CapturedRequest();
        HttpServer server = startServer(200, captured);
        try {
            VersClient client = makeClient(server);
            client.listPublicRepoTags();
            assertEquals("GET", captured.method, "HTTP method should be GET");
            assertNotNull(captured.path, "path should be captured");
            assertTrue(captured.path.startsWith("/"), "path should start with /");
        } finally {
            server.stop(0);
        }
    }

    @Test
    void test_branch_by_tag() throws Exception {
        CapturedRequest captured = new CapturedRequest();
        HttpServer server = startServer(200, captured);
        try {
            VersClient client = makeClient(server);
            client.branchByTag();
            assertEquals("POST", captured.method, "HTTP method should be POST");
            assertNotNull(captured.path, "path should be captured");
            assertTrue(captured.path.startsWith("/"), "path should start with /");
        } finally {
            server.stop(0);
        }
    }

    @Test
    void test_branch_vm() throws Exception {
        CapturedRequest captured = new CapturedRequest();
        HttpServer server = startServer(200, captured);
        try {
            VersClient client = makeClient(server);
            client.branchVm();
            assertEquals("POST", captured.method, "HTTP method should be POST");
            assertNotNull(captured.path, "path should be captured");
            assertTrue(captured.path.startsWith("/"), "path should start with /");
        } finally {
            server.stop(0);
        }
    }

    @Test
    void test_get_repo_tag() throws Exception {
        CapturedRequest captured = new CapturedRequest();
        HttpServer server = startServer(200, captured);
        try {
            VersClient client = makeClient(server);
            client.getRepoTag();
            assertEquals("GET", captured.method, "HTTP method should be GET");
            assertNotNull(captured.path, "path should be captured");
            assertTrue(captured.path.startsWith("/"), "path should start with /");
        } finally {
            server.stop(0);
        }
    }

    @Test
    void test_delete_repo_tag() throws Exception {
        CapturedRequest captured = new CapturedRequest();
        HttpServer server = startServer(200, captured);
        try {
            VersClient client = makeClient(server);
            client.deleteRepoTag();
            assertEquals("DELETE", captured.method, "HTTP method should be DELETE");
            assertNotNull(captured.path, "path should be captured");
            assertTrue(captured.path.startsWith("/"), "path should start with /");
        } finally {
            server.stop(0);
        }
    }

    @Test
    void test_update_repo_tag() throws Exception {
        CapturedRequest captured = new CapturedRequest();
        HttpServer server = startServer(200, captured);
        try {
            VersClient client = makeClient(server);
            client.updateRepoTag();
            assertEquals("PATCH", captured.method, "HTTP method should be PATCH");
            assertNotNull(captured.path, "path should be captured");
            assertTrue(captured.path.startsWith("/"), "path should start with /");
        } finally {
            server.stop(0);
        }
    }

    @Test
    void test_get_repository() throws Exception {
        CapturedRequest captured = new CapturedRequest();
        HttpServer server = startServer(200, captured);
        try {
            VersClient client = makeClient(server);
            client.getRepository();
            assertEquals("GET", captured.method, "HTTP method should be GET");
            assertNotNull(captured.path, "path should be captured");
            assertTrue(captured.path.startsWith("/"), "path should start with /");
        } finally {
            server.stop(0);
        }
    }

    @Test
    void test_delete_repository() throws Exception {
        CapturedRequest captured = new CapturedRequest();
        HttpServer server = startServer(200, captured);
        try {
            VersClient client = makeClient(server);
            client.deleteRepository();
            assertEquals("DELETE", captured.method, "HTTP method should be DELETE");
            assertNotNull(captured.path, "path should be captured");
            assertTrue(captured.path.startsWith("/"), "path should start with /");
        } finally {
            server.stop(0);
        }
    }

    @Test
    void test_list_parent_commits() throws Exception {
        CapturedRequest captured = new CapturedRequest();
        HttpServer server = startServer(200, captured);
        try {
            VersClient client = makeClient(server);
            client.listParentCommits();
            assertEquals("GET", captured.method, "HTTP method should be GET");
            assertNotNull(captured.path, "path should be captured");
            assertTrue(captured.path.startsWith("/"), "path should start with /");
        } finally {
            server.stop(0);
        }
    }

    @Test
    void test_update_vm_state() throws Exception {
        CapturedRequest captured = new CapturedRequest();
        HttpServer server = startServer(200, captured);
        try {
            VersClient client = makeClient(server);
            client.updateVmState();
            assertEquals("PATCH", captured.method, "HTTP method should be PATCH");
            assertNotNull(captured.path, "path should be captured");
            assertTrue(captured.path.startsWith("/"), "path should start with /");
        } finally {
            server.stop(0);
        }
    }

    @Test
    void test_fork_repository() throws Exception {
        CapturedRequest captured = new CapturedRequest();
        HttpServer server = startServer(200, captured);
        try {
            VersClient client = makeClient(server);
            client.forkRepository();
            assertEquals("POST", captured.method, "HTTP method should be POST");
            assertNotNull(captured.path, "path should be captured");
            assertTrue(captured.path.startsWith("/"), "path should start with /");
        } finally {
            server.stop(0);
        }
    }

    @Test
    void test_list_repositories() throws Exception {
        CapturedRequest captured = new CapturedRequest();
        HttpServer server = startServer(200, captured);
        try {
            VersClient client = makeClient(server);
            client.listRepositories();
            assertEquals("GET", captured.method, "HTTP method should be GET");
            assertNotNull(captured.path, "path should be captured");
            assertTrue(captured.path.startsWith("/"), "path should start with /");
        } finally {
            server.stop(0);
        }
    }

    @Test
    void test_create_repository() throws Exception {
        CapturedRequest captured = new CapturedRequest();
        HttpServer server = startServer(200, captured);
        try {
            VersClient client = makeClient(server);
            client.createRepository();
            assertEquals("POST", captured.method, "HTTP method should be POST");
            assertNotNull(captured.path, "path should be captured");
            assertTrue(captured.path.startsWith("/"), "path should start with /");
        } finally {
            server.stop(0);
        }
    }

    @Test
    void test_restore_from_commit() throws Exception {
        CapturedRequest captured = new CapturedRequest();
        HttpServer server = startServer(200, captured);
        try {
            VersClient client = makeClient(server);
            client.restoreFromCommit();
            assertEquals("POST", captured.method, "HTTP method should be POST");
            assertNotNull(captured.path, "path should be captured");
            assertTrue(captured.path.startsWith("/"), "path should start with /");
        } finally {
            server.stop(0);
        }
    }

    @Test
    void test_get_domain() throws Exception {
        CapturedRequest captured = new CapturedRequest();
        HttpServer server = startServer(200, captured);
        try {
            VersClient client = makeClient(server);
            client.getDomain();
            assertEquals("GET", captured.method, "HTTP method should be GET");
            assertNotNull(captured.path, "path should be captured");
            assertTrue(captured.path.startsWith("/"), "path should start with /");
        } finally {
            server.stop(0);
        }
    }

    @Test
    void test_delete_domain() throws Exception {
        CapturedRequest captured = new CapturedRequest();
        HttpServer server = startServer(200, captured);
        try {
            VersClient client = makeClient(server);
            client.deleteDomain();
            assertEquals("DELETE", captured.method, "HTTP method should be DELETE");
            assertNotNull(captured.path, "path should be captured");
            assertTrue(captured.path.startsWith("/"), "path should start with /");
        } finally {
            server.stop(0);
        }
    }

    @Test
    void test_list_tags() throws Exception {
        CapturedRequest captured = new CapturedRequest();
        HttpServer server = startServer(200, captured);
        try {
            VersClient client = makeClient(server);
            client.listTags();
            assertEquals("GET", captured.method, "HTTP method should be GET");
            assertNotNull(captured.path, "path should be captured");
            assertTrue(captured.path.startsWith("/"), "path should start with /");
        } finally {
            server.stop(0);
        }
    }

    @Test
    void test_create_tag() throws Exception {
        CapturedRequest captured = new CapturedRequest();
        HttpServer server = startServer(200, captured);
        try {
            VersClient client = makeClient(server);
            client.createTag();
            assertEquals("POST", captured.method, "HTTP method should be POST");
            assertNotNull(captured.path, "path should be captured");
            assertTrue(captured.path.startsWith("/"), "path should start with /");
        } finally {
            server.stop(0);
        }
    }

    @Test
    void test_list_public_repositories() throws Exception {
        CapturedRequest captured = new CapturedRequest();
        HttpServer server = startServer(200, captured);
        try {
            VersClient client = makeClient(server);
            client.listPublicRepositories();
            assertEquals("GET", captured.method, "HTTP method should be GET");
            assertNotNull(captured.path, "path should be captured");
            assertTrue(captured.path.startsWith("/"), "path should start with /");
        } finally {
            server.stop(0);
        }
    }

    @Test
    void test_get_public_repo_tag() throws Exception {
        CapturedRequest captured = new CapturedRequest();
        HttpServer server = startServer(200, captured);
        try {
            VersClient client = makeClient(server);
            client.getPublicRepoTag();
            assertEquals("GET", captured.method, "HTTP method should be GET");
            assertNotNull(captured.path, "path should be captured");
            assertTrue(captured.path.startsWith("/"), "path should start with /");
        } finally {
            server.stop(0);
        }
    }

    @Test
    void test_get_vm_metadata() throws Exception {
        CapturedRequest captured = new CapturedRequest();
        HttpServer server = startServer(200, captured);
        try {
            VersClient client = makeClient(server);
            client.getVmMetadata();
            assertEquals("GET", captured.method, "HTTP method should be GET");
            assertNotNull(captured.path, "path should be captured");
            assertTrue(captured.path.startsWith("/"), "path should start with /");
        } finally {
            server.stop(0);
        }
    }

    @Test
    void test_list_env_vars() throws Exception {
        CapturedRequest captured = new CapturedRequest();
        HttpServer server = startServer(200, captured);
        try {
            VersClient client = makeClient(server);
            client.listEnvVars();
            assertEquals("GET", captured.method, "HTTP method should be GET");
            assertNotNull(captured.path, "path should be captured");
            assertTrue(captured.path.startsWith("/"), "path should start with /");
        } finally {
            server.stop(0);
        }
    }

    @Test
    void test_set_env_vars() throws Exception {
        CapturedRequest captured = new CapturedRequest();
        HttpServer server = startServer(200, captured);
        try {
            VersClient client = makeClient(server);
            client.setEnvVars();
            assertEquals("PUT", captured.method, "HTTP method should be PUT");
            assertNotNull(captured.path, "path should be captured");
            assertTrue(captured.path.startsWith("/"), "path should start with /");
        } finally {
            server.stop(0);
        }
    }

    @Test
    void test_delete_vm() throws Exception {
        CapturedRequest captured = new CapturedRequest();
        HttpServer server = startServer(200, captured);
        try {
            VersClient client = makeClient(server);
            client.deleteVm();
            assertEquals("DELETE", captured.method, "HTTP method should be DELETE");
            assertNotNull(captured.path, "path should be captured");
            assertTrue(captured.path.startsWith("/"), "path should start with /");
        } finally {
            server.stop(0);
        }
    }

    @Test
    void test_list_commits() throws Exception {
        CapturedRequest captured = new CapturedRequest();
        HttpServer server = startServer(200, captured);
        try {
            VersClient client = makeClient(server);
            client.listCommits();
            assertEquals("GET", captured.method, "HTTP method should be GET");
            assertNotNull(captured.path, "path should be captured");
            assertTrue(captured.path.startsWith("/"), "path should start with /");
        } finally {
            server.stop(0);
        }
    }

    @Test
    void test_get_tag() throws Exception {
        CapturedRequest captured = new CapturedRequest();
        HttpServer server = startServer(200, captured);
        try {
            VersClient client = makeClient(server);
            client.getTag();
            assertEquals("GET", captured.method, "HTTP method should be GET");
            assertNotNull(captured.path, "path should be captured");
            assertTrue(captured.path.startsWith("/"), "path should start with /");
        } finally {
            server.stop(0);
        }
    }

    @Test
    void test_delete_tag() throws Exception {
        CapturedRequest captured = new CapturedRequest();
        HttpServer server = startServer(200, captured);
        try {
            VersClient client = makeClient(server);
            client.deleteTag();
            assertEquals("DELETE", captured.method, "HTTP method should be DELETE");
            assertNotNull(captured.path, "path should be captured");
            assertTrue(captured.path.startsWith("/"), "path should start with /");
        } finally {
            server.stop(0);
        }
    }

    @Test
    void test_update_tag() throws Exception {
        CapturedRequest captured = new CapturedRequest();
        HttpServer server = startServer(200, captured);
        try {
            VersClient client = makeClient(server);
            client.updateTag();
            assertEquals("PATCH", captured.method, "HTTP method should be PATCH");
            assertNotNull(captured.path, "path should be captured");
            assertTrue(captured.path.startsWith("/"), "path should start with /");
        } finally {
            server.stop(0);
        }
    }

    @Test
    void test_branch_by_vm() throws Exception {
        CapturedRequest captured = new CapturedRequest();
        HttpServer server = startServer(200, captured);
        try {
            VersClient client = makeClient(server);
            client.branchByVm();
            assertEquals("POST", captured.method, "HTTP method should be POST");
            assertNotNull(captured.path, "path should be captured");
            assertTrue(captured.path.startsWith("/"), "path should start with /");
        } finally {
            server.stop(0);
        }
    }

    @Test
    void test_delete_env_var() throws Exception {
        CapturedRequest captured = new CapturedRequest();
        HttpServer server = startServer(200, captured);
        try {
            VersClient client = makeClient(server);
            client.deleteEnvVar();
            assertEquals("DELETE", captured.method, "HTTP method should be DELETE");
            assertNotNull(captured.path, "path should be captured");
            assertTrue(captured.path.startsWith("/"), "path should start with /");
        } finally {
            server.stop(0);
        }
    }

    @Test
    void test_exec_vm_stream() throws Exception {
        CapturedRequest captured = new CapturedRequest();
        HttpServer server = startServer(200, captured);
        try {
            VersClient client = makeClient(server);
            client.execVmStream();
            assertEquals("POST", captured.method, "HTTP method should be POST");
            assertNotNull(captured.path, "path should be captured");
            assertTrue(captured.path.startsWith("/"), "path should start with /");
        } finally {
            server.stop(0);
        }
    }

    @Test
    void test_commit_vm() throws Exception {
        CapturedRequest captured = new CapturedRequest();
        HttpServer server = startServer(200, captured);
        try {
            VersClient client = makeClient(server);
            client.commitVm();
            assertEquals("POST", captured.method, "HTTP method should be POST");
            assertNotNull(captured.path, "path should be captured");
            assertTrue(captured.path.startsWith("/"), "path should start with /");
        } finally {
            server.stop(0);
        }
    }

    @Test
    void test_delete_commit() throws Exception {
        CapturedRequest captured = new CapturedRequest();
        HttpServer server = startServer(200, captured);
        try {
            VersClient client = makeClient(server);
            client.deleteCommit();
            assertEquals("DELETE", captured.method, "HTTP method should be DELETE");
            assertNotNull(captured.path, "path should be captured");
            assertTrue(captured.path.startsWith("/"), "path should start with /");
        } finally {
            server.stop(0);
        }
    }

    @Test
    void test_update_commit() throws Exception {
        CapturedRequest captured = new CapturedRequest();
        HttpServer server = startServer(200, captured);
        try {
            VersClient client = makeClient(server);
            client.updateCommit();
            assertEquals("PATCH", captured.method, "HTTP method should be PATCH");
            assertNotNull(captured.path, "path should be captured");
            assertTrue(captured.path.startsWith("/"), "path should start with /");
        } finally {
            server.stop(0);
        }
    }

    @Test
    void test_list_repo_tags() throws Exception {
        CapturedRequest captured = new CapturedRequest();
        HttpServer server = startServer(200, captured);
        try {
            VersClient client = makeClient(server);
            client.listRepoTags();
            assertEquals("GET", captured.method, "HTTP method should be GET");
            assertNotNull(captured.path, "path should be captured");
            assertTrue(captured.path.startsWith("/"), "path should start with /");
        } finally {
            server.stop(0);
        }
    }

    @Test
    void test_create_repo_tag() throws Exception {
        CapturedRequest captured = new CapturedRequest();
        HttpServer server = startServer(200, captured);
        try {
            VersClient client = makeClient(server);
            client.createRepoTag();
            assertEquals("POST", captured.method, "HTTP method should be POST");
            assertNotNull(captured.path, "path should be captured");
            assertTrue(captured.path.startsWith("/"), "path should start with /");
        } finally {
            server.stop(0);
        }
    }

    @Test
    void test_ssh_key() throws Exception {
        CapturedRequest captured = new CapturedRequest();
        HttpServer server = startServer(200, captured);
        try {
            VersClient client = makeClient(server);
            client.sshKey();
            assertEquals("GET", captured.method, "HTTP method should be GET");
            assertNotNull(captured.path, "path should be captured");
            assertTrue(captured.path.startsWith("/"), "path should start with /");
        } finally {
            server.stop(0);
        }
    }

    @Test
    void test_exec_vm() throws Exception {
        CapturedRequest captured = new CapturedRequest();
        HttpServer server = startServer(200, captured);
        try {
            VersClient client = makeClient(server);
            client.execVm();
            assertEquals("POST", captured.method, "HTTP method should be POST");
            assertNotNull(captured.path, "path should be captured");
            assertTrue(captured.path.startsWith("/"), "path should start with /");
        } finally {
            server.stop(0);
        }
    }

    @Test
    void test_set_repository_visibility() throws Exception {
        CapturedRequest captured = new CapturedRequest();
        HttpServer server = startServer(200, captured);
        try {
            VersClient client = makeClient(server);
            client.setRepositoryVisibility();
            assertEquals("PATCH", captured.method, "HTTP method should be PATCH");
            assertNotNull(captured.path, "path should be captured");
            assertTrue(captured.path.startsWith("/"), "path should start with /");
        } finally {
            server.stop(0);
        }
    }

    @Test
    void test_list_vms() throws Exception {
        CapturedRequest captured = new CapturedRequest();
        HttpServer server = startServer(200, captured);
        try {
            VersClient client = makeClient(server);
            client.listVms();
            assertEquals("GET", captured.method, "HTTP method should be GET");
            assertNotNull(captured.path, "path should be captured");
            assertTrue(captured.path.startsWith("/"), "path should start with /");
        } finally {
            server.stop(0);
        }
    }

    @Test
    void test_list_domains() throws Exception {
        CapturedRequest captured = new CapturedRequest();
        HttpServer server = startServer(200, captured);
        try {
            VersClient client = makeClient(server);
            client.listDomains();
            assertEquals("GET", captured.method, "HTTP method should be GET");
            assertNotNull(captured.path, "path should be captured");
            assertTrue(captured.path.startsWith("/"), "path should start with /");
        } finally {
            server.stop(0);
        }
    }

    @Test
    void test_create_domain() throws Exception {
        CapturedRequest captured = new CapturedRequest();
        HttpServer server = startServer(200, captured);
        try {
            VersClient client = makeClient(server);
            client.createDomain();
            assertEquals("POST", captured.method, "HTTP method should be POST");
            assertNotNull(captured.path, "path should be captured");
            assertTrue(captured.path.startsWith("/"), "path should start with /");
        } finally {
            server.stop(0);
        }
    }

    @Test
    void test_vm_status() throws Exception {
        CapturedRequest captured = new CapturedRequest();
        HttpServer server = startServer(200, captured);
        try {
            VersClient client = makeClient(server);
            client.vmStatus();
            assertEquals("GET", captured.method, "HTTP method should be GET");
            assertNotNull(captured.path, "path should be captured");
            assertTrue(captured.path.startsWith("/"), "path should start with /");
        } finally {
            server.stop(0);
        }
    }

    @Test
    void test_get_public_repository() throws Exception {
        CapturedRequest captured = new CapturedRequest();
        HttpServer server = startServer(200, captured);
        try {
            VersClient client = makeClient(server);
            client.getPublicRepository();
            assertEquals("GET", captured.method, "HTTP method should be GET");
            assertNotNull(captured.path, "path should be captured");
            assertTrue(captured.path.startsWith("/"), "path should start with /");
        } finally {
            server.stop(0);
        }
    }

    @Test
    void test_branch_by_commit() throws Exception {
        CapturedRequest captured = new CapturedRequest();
        HttpServer server = startServer(200, captured);
        try {
            VersClient client = makeClient(server);
            client.branchByCommit();
            assertEquals("POST", captured.method, "HTTP method should be POST");
            assertNotNull(captured.path, "path should be captured");
            assertTrue(captured.path.startsWith("/"), "path should start with /");
        } finally {
            server.stop(0);
        }
    }

    // ── Error handling tests ────────────────────────────────────────────

    @Test
    void test_error_400() throws Exception {
        CapturedRequest captured = new CapturedRequest();
        HttpServer server = startServer(400, captured);
        try {
            VersClient client = makeClient(server);
            assertThrows(Errors.BadRequestError.class, () -> {
                client.resizeVmDisk();
            });
        } finally {
            server.stop(0);
        }
    }

    @Test
    void test_error_404() throws Exception {
        CapturedRequest captured = new CapturedRequest();
        HttpServer server = startServer(404, captured);
        try {
            VersClient client = makeClient(server);
            assertThrows(Errors.NotFoundError.class, () -> {
                client.resizeVmDisk();
            });
        } finally {
            server.stop(0);
        }
    }

    @Test
    void test_error_500() throws Exception {
        CapturedRequest captured = new CapturedRequest();
        HttpServer server = startServer(500, captured);
        try {
            VersClient client = makeClient(server);
            assertThrows(Errors.InternalServerError.class, () -> {
                client.resizeVmDisk();
            });
        } finally {
            server.stop(0);
        }
    }

}
