// Generated by Sterling SDK Generator
// Orchestrator Control Plane API v0.1.0

package com.vers.sdk;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonValue;

import java.util.List;
import java.util.Map;

/**
 * Model classes for Orchestrator Control Plane API.
 */
public final class Models {

    private Models() {} // Utility class

    /**
     * Response body for POST /api/v1/repositories/fork
     */
    public static class ForkRepositoryResponse {
        /** The new commit in your org (snapshot of the forked VM) */
        @JsonProperty("commit_id")
        private String commit_id;

        /** Full reference: repo_name:tag_name */
        @JsonProperty("reference")
        private String reference;

        /** The new repository name in your org */
        @JsonProperty("repo_name")
        private String repo_name;

        /** The tag name pointing to the forked commit */
        @JsonProperty("tag_name")
        private String tag_name;

        /** The new VM that was created from the fork */
        @JsonProperty("vm_id")
        private String vm_id;

        public ForkRepositoryResponse() {}

        public String getCommitId() { return commit_id; }
        public void setCommitId(String commit_id) { this.commit_id = commit_id; }

        public String getReference() { return reference; }
        public void setReference(String reference) { this.reference = reference; }

        public String getRepoName() { return repo_name; }
        public void setRepoName(String repo_name) { this.repo_name = repo_name; }

        public String getTagName() { return tag_name; }
        public void setTagName(String tag_name) { this.tag_name = tag_name; }

        public String getVmId() { return vm_id; }
        public void setVmId(String vm_id) { this.vm_id = vm_id; }

    }

    /**
     * Response body for GET /api/vm/{vm_id}/ssh_key
     */
    public static class VmSshKeyResponse {
        /** The SSH port that will be DNAT'd to the VM's netns (and, in turn, to its TAP device) */
        @JsonProperty("ssh_port")
        private Integer ssh_port;

        /** Private SSH key in stringified OpenSSH format */
        @JsonProperty("ssh_private_key")
        private String ssh_private_key;

        public VmSshKeyResponse() {}

        public Integer getSshPort() { return ssh_port; }
        public void setSshPort(Integer ssh_port) { this.ssh_port = ssh_port; }

        public String getSshPrivateKey() { return ssh_private_key; }
        public void setSshPrivateKey(String ssh_private_key) { this.ssh_private_key = ssh_private_key; }

    }

    /**
     * The state of a VM
     */
    public enum VmState {
        BOOTING("booting"),
        RUNNING("running"),
        PAUSED("paused"),
        SLEEPING("sleeping"),
        DEAD("dead");

        private final String value;

        VmState(String value) {
            this.value = value;
        }

        @JsonValue
        public String getValue() {
            return value;
        }

        @Override
        public String toString() {
            return value;
        }
    }

    /**
     * Possible options for the state requested in PATCH /api/vm/{vm_id}/state
     */
    public enum VmUpdateStateEnum {
        PAUSED("Paused"),
        RUNNING("Running");

        private final String value;

        VmUpdateStateEnum(String value) {
            this.value = value;
        }

        @JsonValue
        public String getValue() {
            return value;
        }

        @Override
        public String toString() {
            return value;
        }
    }

    /**
     * Request body for PATCH /api/vm/{vm_id}/state
     */
    public static class VmUpdateStateRequest {
        /** The requested state for the VM */
        @JsonProperty("state")
        private VmUpdateStateEnum state;

        public VmUpdateStateRequest() {}

        public VmUpdateStateEnum getState() { return state; }
        public void setState(VmUpdateStateEnum state) { this.state = state; }

    }

    /**
     * 
     */
    public static class ErrorResponse {
        /** Reason of error */
        @JsonProperty("error")
        private String error;

        /** Is always: false */
        @JsonProperty("success")
        private Boolean success;

        public ErrorResponse() {}

        public String getError() { return error; }
        public void setError(String error) { this.error = error; }

        public Boolean getSuccess() { return success; }
        public void setSuccess(Boolean success) { this.success = success; }

    }

    /**
     * Request body for PATCH /commits/{commit_id}
     */
    public static class UpdateCommitRequest {
        @JsonProperty("is_public")
        private Boolean is_public;

        public UpdateCommitRequest() {}

        public Boolean getIsPublic() { return is_public; }
        public void setIsPublic(Boolean is_public) { this.is_public = is_public; }

    }

    /**
     * Response body for GET /env_vars and PUT /env_vars.
     */
    public static class EnvVarsResponse {
        /** All environment variables currently set for the authenticated user. */
        @JsonProperty("vars")
        private Map<String, Object> vars;

        public EnvVarsResponse() {}

        public Map<String, Object> getVars() { return vars; }
        public void setVars(Map<String, Object> vars) { this.vars = vars; }

    }

    /**
     * Response body for POST /api/v1/repositories
     */
    public static class CreateRepositoryResponse {
        /** The name of the repository */
        @JsonProperty("name")
        private String name;

        /** The ID of the newly created repository */
        @JsonProperty("repo_id")
        private String repo_id;

        public CreateRepositoryResponse() {}

        public String getName() { return name; }
        public void setName(String name) { this.name = name; }

        public String getRepoId() { return repo_id; }
        public void setRepoId(String repo_id) { this.repo_id = repo_id; }

    }

    /**
     * Request body for POST /api/v1/repositories
     */
    public static class CreateRepositoryRequest {
        /** Optional description of the repository */
        @JsonProperty("description")
        private Object description;

        /** The name of the repository (alphanumeric, hyphens, underscores, dots, 1-64 chars) */
        @JsonProperty("name")
        private String name;

        public CreateRepositoryRequest() {}

        public Object getDescription() { return description; }
        public void setDescription(Object description) { this.description = description; }

        public String getName() { return name; }
        public void setName(String name) { this.name = name; }

    }

    /**
     * Response type for domain operations.
     */
    public static class DomainResponse {
        @JsonProperty("created_at")
        private String created_at;

        @JsonProperty("domain")
        private String domain;

        @JsonProperty("domain_id")
        private String domain_id;

        @JsonProperty("vm_id")
        private String vm_id;

        public DomainResponse() {}

        public String getCreatedAt() { return created_at; }
        public void setCreatedAt(String created_at) { this.created_at = created_at; }

        public String getDomain() { return domain; }
        public void setDomain(String domain) { this.domain = domain; }

        public String getDomainId() { return domain_id; }
        public void setDomainId(String domain_id) { this.domain_id = domain_id; }

        public String getVmId() { return vm_id; }
        public void setVmId(String vm_id) { this.vm_id = vm_id; }

    }

    /**
     * Public repository information (includes owner org name for namespacing)
     */
    public static class PublicRepositoryInfo {
        /** When the repository was created */
        @JsonProperty("created_at")
        private String created_at;

        /** Optional description */
        @JsonProperty("description")
        private Object description;

        /** Full reference: org_name/repo_name */
        @JsonProperty("full_name")
        private String full_name;

        /** The repository name */
        @JsonProperty("name")
        private String name;

        /** The owning organization's name (namespace) */
        @JsonProperty("org_name")
        private String org_name;

        /** The repository's unique identifier */
        @JsonProperty("repo_id")
        private String repo_id;

        public PublicRepositoryInfo() {}

        public String getCreatedAt() { return created_at; }
        public void setCreatedAt(String created_at) { this.created_at = created_at; }

        public Object getDescription() { return description; }
        public void setDescription(Object description) { this.description = description; }

        public String getFullName() { return full_name; }
        public void setFullName(String full_name) { this.full_name = full_name; }

        public String getName() { return name; }
        public void setName(String name) { this.name = name; }

        public String getOrgName() { return org_name; }
        public void setOrgName(String org_name) { this.org_name = org_name; }

        public String getRepoId() { return repo_id; }
        public void setRepoId(String repo_id) { this.repo_id = repo_id; }

    }

    /**
     * Response body for GET /api/v1/commit_tags
     */
    public static class ListTagsResponse {
        /** List of all tags in the user's organization */
        @JsonProperty("tags")
        private List<TagInfo> tags;

        public ListTagsResponse() {}

        public List<TagInfo> getTags() { return tags; }
        public void setTags(List<TagInfo> tags) { this.tags = tags; }

    }

    /**
     * Request body for creating a tag within a repository: POST /api/v1/repositories/{repo_name}/tags
     */
    public static class CreateRepoTagRequest {
        /** The commit ID this tag should point to */
        @JsonProperty("commit_id")
        private String commit_id;

        /** Optional description of what this tag represents */
        @JsonProperty("description")
        private Object description;

        /** The tag name (e.g. 'latest', 'v1.0') */
        @JsonProperty("tag_name")
        private String tag_name;

        public CreateRepoTagRequest() {}

        public String getCommitId() { return commit_id; }
        public void setCommitId(String commit_id) { this.commit_id = commit_id; }

        public Object getDescription() { return description; }
        public void setDescription(Object description) { this.description = description; }

        public String getTagName() { return tag_name; }
        public void setTagName(String tag_name) { this.tag_name = tag_name; }

    }

    /**
     * Request body for POST /api/v1/repositories/fork
     */
    public static class ForkRepositoryRequest {
        /** Name for the new repository in your org (defaults to source_repo if omitted) */
        @JsonProperty("repo_name")
        private Object repo_name;

        /** The organization that owns the source public repository */
        @JsonProperty("source_org")
        private String source_org;

        /** The source repository name */
        @JsonProperty("source_repo")
        private String source_repo;

        /** The tag to fork (e.g. 'latest', 'v1.0') */
        @JsonProperty("source_tag")
        private String source_tag;

        /** Tag name in the new repo (defaults to source_tag if omitted) */
        @JsonProperty("tag_name")
        private Object tag_name;

        public ForkRepositoryRequest() {}

        public Object getRepoName() { return repo_name; }
        public void setRepoName(Object repo_name) { this.repo_name = repo_name; }

        public String getSourceOrg() { return source_org; }
        public void setSourceOrg(String source_org) { this.source_org = source_org; }

        public String getSourceRepo() { return source_repo; }
        public void setSourceRepo(String source_repo) { this.source_repo = source_repo; }

        public String getSourceTag() { return source_tag; }
        public void setSourceTag(String source_tag) { this.source_tag = source_tag; }

        public Object getTagName() { return tag_name; }
        public void setTagName(Object tag_name) { this.tag_name = tag_name; }

    }

    /**
     * 
     */
    public static class VmCommitEntity {
        @JsonProperty("created_at")
        private String created_at;

        @JsonProperty("description")
        private Object description;

        /** The commit that this commit's parent VM was started from, if any. Intended to optimize traversing the commit tree. */
        @JsonProperty("grandparent_commit_id")
        private Object grandparent_commit_id;

        @JsonProperty("id")
        private String id;

        /** Whether this commit is publicly accessible (readable/restorable by anyone). */
        @JsonProperty("is_public")
        private Boolean is_public;

        @JsonProperty("name")
        private String name;

        /** api key id. */
        @JsonProperty("owner_id")
        private String owner_id;

        /** The VM that this commit was created from, if any. */
        @JsonProperty("parent_vm_id")
        private Object parent_vm_id;

        public VmCommitEntity() {}

        public String getCreatedAt() { return created_at; }
        public void setCreatedAt(String created_at) { this.created_at = created_at; }

        public Object getDescription() { return description; }
        public void setDescription(Object description) { this.description = description; }

        public Object getGrandparentCommitId() { return grandparent_commit_id; }
        public void setGrandparentCommitId(Object grandparent_commit_id) { this.grandparent_commit_id = grandparent_commit_id; }

        public String getId() { return id; }
        public void setId(String id) { this.id = id; }

        public Boolean getIsPublic() { return is_public; }
        public void setIsPublic(Boolean is_public) { this.is_public = is_public; }

        public String getName() { return name; }
        public void setName(String name) { this.name = name; }

        public String getOwnerId() { return owner_id; }
        public void setOwnerId(String owner_id) { this.owner_id = owner_id; }

        public Object getParentVmId() { return parent_vm_id; }
        public void setParentVmId(Object parent_vm_id) { this.parent_vm_id = parent_vm_id; }

    }

    /**
     * Query params for GET /api/vm/{vm_id}/exec/logs
     */
    public static class VmExecLogQuery {
        /** Maximum number of entries to return (server applies caps). */
        @JsonProperty("max_entries")
        private Object max_entries;

        /** Byte offset into the log file to start reading from. */
        @JsonProperty("offset")
        private Object offset;

        /** Skip waiting for boot state (mirrors exec). */
        @JsonProperty("skip_wait_boot")
        private Object skip_wait_boot;

        @JsonProperty("stream")
        private Object stream;

        public VmExecLogQuery() {}

        public Object getMaxEntries() { return max_entries; }
        public void setMaxEntries(Object max_entries) { this.max_entries = max_entries; }

        public Object getOffset() { return offset; }
        public void setOffset(Object offset) { this.offset = offset; }

        public Object getSkipWaitBoot() { return skip_wait_boot; }
        public void setSkipWaitBoot(Object skip_wait_boot) { this.skip_wait_boot = skip_wait_boot; }

        public Object getStream() { return stream; }
        public void setStream(Object stream) { this.stream = stream; }

    }

    /**
     * Tag information returned in list and get operations
     */
    public static class TagInfo {
        /** The commit ID this tag currently points to */
        @JsonProperty("commit_id")
        private String commit_id;

        /** When the tag was created */
        @JsonProperty("created_at")
        private String created_at;

        /** Optional description of what this tag represents */
        @JsonProperty("description")
        private Object description;

        /** The tag's unique identifier */
        @JsonProperty("tag_id")
        private String tag_id;

        /** The name of the tag */
        @JsonProperty("tag_name")
        private String tag_name;

        /** When the tag was last updated (moved to different commit or description changed) */
        @JsonProperty("updated_at")
        private String updated_at;

        public TagInfo() {}

        public String getCommitId() { return commit_id; }
        public void setCommitId(String commit_id) { this.commit_id = commit_id; }

        public String getCreatedAt() { return created_at; }
        public void setCreatedAt(String created_at) { this.created_at = created_at; }

        public Object getDescription() { return description; }
        public void setDescription(Object description) { this.description = description; }

        public String getTagId() { return tag_id; }
        public void setTagId(String tag_id) { this.tag_id = tag_id; }

        public String getTagName() { return tag_name; }
        public void setTagName(String tag_name) { this.tag_name = tag_name; }

        public String getUpdatedAt() { return updated_at; }
        public void setUpdatedAt(String updated_at) { this.updated_at = updated_at; }

    }

    /**
     * 
     */
    public static class ListCommitsResponse {
        @JsonProperty("commits")
        private List<CommitInfo> commits;

        @JsonProperty("limit")
        private Long limit;

        @JsonProperty("offset")
        private Long offset;

        @JsonProperty("total")
        private Long total;

        public ListCommitsResponse() {}

        public List<CommitInfo> getCommits() { return commits; }
        public void setCommits(List<CommitInfo> commits) { this.commits = commits; }

        public Long getLimit() { return limit; }
        public void setLimit(Long limit) { this.limit = limit; }

        public Long getOffset() { return offset; }
        public void setOffset(Long offset) { this.offset = offset; }

        public Long getTotal() { return total; }
        public void setTotal(Long total) { this.total = total; }

    }

    /**
     * Response body for GET /api/v1/repositories/{repo_name}/tags
     */
    public static class ListRepoTagsResponse {
        /** The repository name */
        @JsonProperty("repository")
        private String repository;

        /** List of tags in this repository */
        @JsonProperty("tags")
        private List<RepoTagInfo> tags;

        public ListRepoTagsResponse() {}

        public String getRepository() { return repository; }
        public void setRepository(String repository) { this.repository = repository; }

        public List<RepoTagInfo> getTags() { return tags; }
        public void setTags(List<RepoTagInfo> tags) { this.tags = tags; }

    }

    /**
     * Individual log entry describing emitted stdout/stderr chunk.
     */
    public static class VmExecLogEntry {
        /** Base64-encoded bytes from stdout/stderr chunk. */
        @JsonProperty("data_b64")
        private String data_b64;

        @JsonProperty("exec_id")
        private Object exec_id;

        @JsonProperty("stream")
        private VmExecLogStream stream;

        @JsonProperty("timestamp")
        private String timestamp;

        public VmExecLogEntry() {}

        public String getDataB64() { return data_b64; }
        public void setDataB64(String data_b64) { this.data_b64 = data_b64; }

        public Object getExecId() { return exec_id; }
        public void setExecId(Object exec_id) { this.exec_id = exec_id; }

        public VmExecLogStream getStream() { return stream; }
        public void setStream(VmExecLogStream stream) { this.stream = stream; }

        public String getTimestamp() { return timestamp; }
        public void setTimestamp(String timestamp) { this.timestamp = timestamp; }

    }

    /**
     * Streams available for exec logging.
     */
    public enum VmExecLogStream {
        STDOUT("stdout"),
        STDERR("stderr");

        private final String value;

        VmExecLogStream(String value) {
            this.value = value;
        }

        @JsonValue
        public String getValue() {
            return value;
        }

        @Override
        public String toString() {
            return value;
        }
    }

    /**
     * Response body for POST /api/vm/{vm_id}/exec
     */
    public static class VmExecResponse {
        /** Exec identifier associated with this run. */
        @JsonProperty("exec_id")
        private Object exec_id;

        /** Exit code returned by the command. */
        @JsonProperty("exit_code")
        private Integer exit_code;

        /** UTF-8 decoded stderr (lossy). */
        @JsonProperty("stderr")
        private String stderr;

        /** UTF-8 decoded stdout (lossy). */
        @JsonProperty("stdout")
        private String stdout;

        public VmExecResponse() {}

        public Object getExecId() { return exec_id; }
        public void setExecId(Object exec_id) { this.exec_id = exec_id; }

        public Integer getExitCode() { return exit_code; }
        public void setExitCode(Integer exit_code) { this.exit_code = exit_code; }

        public String getStderr() { return stderr; }
        public void setStderr(String stderr) { this.stderr = stderr; }

        public String getStdout() { return stdout; }
        public void setStdout(String stdout) { this.stdout = stdout; }

    }

    /**
     * Request body for POST /api/vm/{vm_id}/exec/stream/attach
     */
    public static class VmExecStreamAttachRequest {
        /** Optional cursor to resume from (exclusive). If omitted, the full retained backlog is replayed. */
        @JsonProperty("cursor")
        private Object cursor;

        /** Identifier of the exec stream session to reattach to. */
        @JsonProperty("exec_id")
        private String exec_id;

        /** Start streaming after the latest retained chunk (ignores cursor). */
        @JsonProperty("from_latest")
        private Object from_latest;

        public VmExecStreamAttachRequest() {}

        public Object getCursor() { return cursor; }
        public void setCursor(Object cursor) { this.cursor = cursor; }

        public String getExecId() { return exec_id; }
        public void setExecId(String exec_id) { this.exec_id = exec_id; }

        public Object getFromLatest() { return from_latest; }
        public void setFromLatest(Object from_latest) { this.from_latest = from_latest; }

    }

    /**
     * Request body for POST /api/vm/{vm_id}/exec
     */
    public static class VmExecRequest {
        /** Command and arguments to execute. */
        @JsonProperty("command")
        private List<String> command;

        /** Optional environment variables to set for the process. */
        @JsonProperty("env")
        private Object env;

        /** Optional exec identifier for tracking. */
        @JsonProperty("exec_id")
        private Object exec_id;

        /** Optional stdin payload passed to the command. */
        @JsonProperty("stdin")
        private Object stdin;

        /** Timeout in seconds (0 = no timeout). */
        @JsonProperty("timeout_secs")
        private Object timeout_secs;

        /** Optional working directory for the command. */
        @JsonProperty("working_dir")
        private Object working_dir;

        public VmExecRequest() {}

        public List<String> getCommand() { return command; }
        public void setCommand(List<String> command) { this.command = command; }

        public Object getEnv() { return env; }
        public void setEnv(Object env) { this.env = env; }

        public Object getExecId() { return exec_id; }
        public void setExecId(Object exec_id) { this.exec_id = exec_id; }

        public Object getStdin() { return stdin; }
        public void setStdin(Object stdin) { this.stdin = stdin; }

        public Object getTimeoutSecs() { return timeout_secs; }
        public void setTimeoutSecs(Object timeout_secs) { this.timeout_secs = timeout_secs; }

        public Object getWorkingDir() { return working_dir; }
        public void setWorkingDir(Object working_dir) { this.working_dir = working_dir; }

    }

    /**
     * 
     */
    public static class NewVmsResponse {
        @JsonProperty("vms")
        private List<NewVmResponse> vms;

        public NewVmsResponse() {}

        public List<NewVmResponse> getVms() { return vms; }
        public void setVms(List<NewVmResponse> vms) { this.vms = vms; }

    }

    /**
     * Request body for PATCH /api/v1/repositories/{repo_name}/visibility
     */
    public static class SetRepositoryVisibilityRequest {
        /** Whether the repository should be publicly visible */
        @JsonProperty("is_public")
        private Boolean is_public;

        public SetRepositoryVisibilityRequest() {}

        public Boolean getIsPublic() { return is_public; }
        public void setIsPublic(Boolean is_public) { this.is_public = is_public; }

    }

    /**
     * Request body for PATCH /api/v1/repositories/{repo_name}/tags/{tag_name}
     */
    public static class UpdateRepoTagRequest {
        /** Optional new commit ID to move the tag to */
        @JsonProperty("commit_id")
        private Object commit_id;

        /** Optional new description for the tag. Send `null` to clear. */
        @JsonProperty("description")
        private Object description;

        public UpdateRepoTagRequest() {}

        public Object getCommitId() { return commit_id; }
        public void setCommitId(Object commit_id) { this.commit_id = commit_id; }

        public Object getDescription() { return description; }
        public void setDescription(Object description) { this.description = description; }

    }

    /**
     * Response body for new VM requests (new_root, from_commit, branch)
     */
    public static class NewVmResponse {
        @JsonProperty("vm_id")
        private String vm_id;

        public NewVmResponse() {}

        public String getVmId() { return vm_id; }
        public void setVmId(String vm_id) { this.vm_id = vm_id; }

    }

    /**
     * Response body for GET /api/v1/public/repositories
     */
    public static class ListPublicRepositoriesResponse {
        @JsonProperty("repositories")
        private List<PublicRepositoryInfo> repositories;

        public ListPublicRepositoriesResponse() {}

        public List<PublicRepositoryInfo> getRepositories() { return repositories; }
        public void setRepositories(List<PublicRepositoryInfo> repositories) { this.repositories = repositories; }

    }

    /**
     * Request body for POST /api/v1/commit_tags
     */
    public static class CreateTagRequest {
        /** The commit ID this tag should point to */
        @JsonProperty("commit_id")
        private String commit_id;

        /** Optional description of what this tag represents */
        @JsonProperty("description")
        private Object description;

        /** The name of the tag (alphanumeric, hyphens, underscores, dots, 1-64 chars) */
        @JsonProperty("tag_name")
        private String tag_name;

        public CreateTagRequest() {}

        public String getCommitId() { return commit_id; }
        public void setCommitId(String commit_id) { this.commit_id = commit_id; }

        public Object getDescription() { return description; }
        public void setDescription(Object description) { this.description = description; }

        public String getTagName() { return tag_name; }
        public void setTagName(String tag_name) { this.tag_name = tag_name; }

    }

    /**
     * Request body for POST /api/v1/vm/from_commit
     * This is a union type — exactly one field should be set.
     */
    public static class FromCommitVmRequest {
        @JsonProperty("commit_id")
        private String commit_id;

        public String getCommitId() { return commit_id; }
        public void setCommitId(String commit_id) { this.commit_id = commit_id; }

        @JsonProperty("tag_name")
        private String tag_name;

        public String getTagName() { return tag_name; }
        public void setTagName(String tag_name) { this.tag_name = tag_name; }

        @JsonProperty("ref")
        private String ref;

        public String getRef() { return ref; }
        public void setRef(String ref) { this.ref = ref; }

    }

    /**
     * Response body for POST /api/v1/repositories/{repo_name}/tags
     */
    public static class CreateRepoTagResponse {
        /** The commit ID this tag points to */
        @JsonProperty("commit_id")
        private String commit_id;

        /** Full reference in image_name:tag format */
        @JsonProperty("reference")
        private String reference;

        /** The ID of the newly created tag */
        @JsonProperty("tag_id")
        private String tag_id;

        public CreateRepoTagResponse() {}

        public String getCommitId() { return commit_id; }
        public void setCommitId(String commit_id) { this.commit_id = commit_id; }

        public String getReference() { return reference; }
        public void setReference(String reference) { this.reference = reference; }

        public String getTagId() { return tag_id; }
        public void setTagId(String tag_id) { this.tag_id = tag_id; }

    }

    /**
     * 
     */
    public static class CommitInfo {
        @JsonProperty("commit_id")
        private String commit_id;

        @JsonProperty("created_at")
        private String created_at;

        @JsonProperty("description")
        private Object description;

        @JsonProperty("grandparent_commit_id")
        private Object grandparent_commit_id;

        @JsonProperty("is_public")
        private Boolean is_public;

        @JsonProperty("name")
        private String name;

        @JsonProperty("owner_id")
        private String owner_id;

        @JsonProperty("parent_vm_id")
        private Object parent_vm_id;

        public CommitInfo() {}

        public String getCommitId() { return commit_id; }
        public void setCommitId(String commit_id) { this.commit_id = commit_id; }

        public String getCreatedAt() { return created_at; }
        public void setCreatedAt(String created_at) { this.created_at = created_at; }

        public Object getDescription() { return description; }
        public void setDescription(Object description) { this.description = description; }

        public Object getGrandparentCommitId() { return grandparent_commit_id; }
        public void setGrandparentCommitId(Object grandparent_commit_id) { this.grandparent_commit_id = grandparent_commit_id; }

        public Boolean getIsPublic() { return is_public; }
        public void setIsPublic(Boolean is_public) { this.is_public = is_public; }

        public String getName() { return name; }
        public void setName(String name) { this.name = name; }

        public String getOwnerId() { return owner_id; }
        public void setOwnerId(String owner_id) { this.owner_id = owner_id; }

        public Object getParentVmId() { return parent_vm_id; }
        public void setParentVmId(Object parent_vm_id) { this.parent_vm_id = parent_vm_id; }

    }

    /**
     * Request body for POST /api/v1/domains
     */
    public static class CreateDomainRequest {
        @JsonProperty("domain")
        private String domain;

        @JsonProperty("vm_id")
        private String vm_id;

        public CreateDomainRequest() {}

        public String getDomain() { return domain; }
        public void setDomain(String domain) { this.domain = domain; }

        public String getVmId() { return vm_id; }
        public void setVmId(String vm_id) { this.vm_id = vm_id; }

    }

    /**
     * Response body for DELETE /api/v1/domains/{domain_id}
     */
    public static class DeleteDomainResponse {
        @JsonProperty("domain_id")
        private String domain_id;

        public DeleteDomainResponse() {}

        public String getDomainId() { return domain_id; }
        public void setDomainId(String domain_id) { this.domain_id = domain_id; }

    }

    /**
     * Response body for GET /api/v1/repositories
     */
    public static class ListRepositoriesResponse {
        /** List of all repositories in the user's organization */
        @JsonProperty("repositories")
        private List<RepositoryInfo> repositories;

        public ListRepositoriesResponse() {}

        public List<RepositoryInfo> getRepositories() { return repositories; }
        public void setRepositories(List<RepositoryInfo> repositories) { this.repositories = repositories; }

    }

    /**
     * Repository information returned in list and get operations
     */
    public static class RepositoryInfo {
        /** When the repository was created */
        @JsonProperty("created_at")
        private String created_at;

        /** Optional description */
        @JsonProperty("description")
        private Object description;

        /** Whether this repository is publicly visible */
        @JsonProperty("is_public")
        private Boolean is_public;

        /** The repository name */
        @JsonProperty("name")
        private String name;

        /** The repository's unique identifier */
        @JsonProperty("repo_id")
        private String repo_id;

        public RepositoryInfo() {}

        public String getCreatedAt() { return created_at; }
        public void setCreatedAt(String created_at) { this.created_at = created_at; }

        public Object getDescription() { return description; }
        public void setDescription(Object description) { this.description = description; }

        public Boolean getIsPublic() { return is_public; }
        public void setIsPublic(Boolean is_public) { this.is_public = is_public; }

        public String getName() { return name; }
        public void setName(String name) { this.name = name; }

        public String getRepoId() { return repo_id; }
        public void setRepoId(String repo_id) { this.repo_id = repo_id; }

    }

    /**
     * Request body for PATCH /api/v1/commit_tags/{tag_name}  For `description`: - Field absent from JSON → don't change the description - Field present as `null` → clear the description - Field present as `'text'` → set the description to 'text'
     */
    public static class UpdateTagRequest {
        /** Optional new commit ID to move the tag to */
        @JsonProperty("commit_id")
        private Object commit_id;

        /** Optional new description for the tag. Send `null` to clear an existing description. */
        @JsonProperty("description")
        private Object description;

        public UpdateTagRequest() {}

        public Object getCommitId() { return commit_id; }
        public void setCommitId(Object commit_id) { this.commit_id = commit_id; }

        public Object getDescription() { return description; }
        public void setDescription(Object description) { this.description = description; }

    }

    /**
     * 
     */
    public static class NewRootRequest {
        @JsonProperty("vm_config")
        private VmCreateVmConfig vm_config;

        public NewRootRequest() {}

        public VmCreateVmConfig getVmConfig() { return vm_config; }
        public void setVmConfig(VmCreateVmConfig vm_config) { this.vm_config = vm_config; }

    }

    /**
     * Request body for PUT /env_vars — sets (upserts) one or more environment variables.  # Lifecycle model  Environment variables are written to `/etc/environment` inside a VM **once at boot time** via a vsock `WriteFile` request. They are **not** live-synced to running VMs. This is intentional: VMs are ephemeral (create → use → destroy/branch), so env var changes naturally take effect on the next VM.  The `replace` flag exists so callers can atomically express 'I want exactly these variables and nothing else' without having to DELETE each stale key individually. Without it, the only way to remove a variable from future VMs is a separate `DELETE /env_vars/{key}` call per key.
     */
    public static class SetEnvVarsRequest {
        /** If true, delete all existing variables before writing the new set. This gives 'set exactly these vars' semantics. Default: false (upsert). */
        @JsonProperty("replace")
        private Boolean replace;

        /** Key-value pairs to set. Keys must be valid shell identifiers (`^[A-Za-z_][A-Za-z0-9_]*$`, max 256 chars). Values max 8192 chars.  When `replace` is false (default): existing keys are overwritten, keys not mentioned are left untouched (upsert semantics).  When `replace` is true: all existing variables are deleted first, then only the provided vars are stored (replace-all semantics). */
        @JsonProperty("vars")
        private Map<String, Object> vars;

        public SetEnvVarsRequest() {}

        public Boolean getReplace() { return replace; }
        public void setReplace(Boolean replace) { this.replace = replace; }

        public Map<String, Object> getVars() { return vars; }
        public void setVars(Map<String, Object> vars) { this.vars = vars; }

    }

    /**
     * 
     */
    public static class VM {
        @JsonProperty("created_at")
        private String created_at;

        @JsonProperty("owner_id")
        private String owner_id;

        @JsonProperty("state")
        private VmState state;

        @JsonProperty("vm_id")
        private String vm_id;

        public VM() {}

        public String getCreatedAt() { return created_at; }
        public void setCreatedAt(String created_at) { this.created_at = created_at; }

        public String getOwnerId() { return owner_id; }
        public void setOwnerId(String owner_id) { this.owner_id = owner_id; }

        public VmState getState() { return state; }
        public void setState(VmState state) { this.state = state; }

        public String getVmId() { return vm_id; }
        public void setVmId(String vm_id) { this.vm_id = vm_id; }

    }

    /**
     * Struct representing configuration options common to all VMs
     */
    public static class VmCreateVmConfig {
        /** The disk size, in MiB. */
        @JsonProperty("fs_size_mib")
        private Object fs_size_mib;

        /** The filesystem base image name. Currently, must be 'default' */
        @JsonProperty("image_name")
        private Object image_name;

        /** The kernel name. Currently, must be 'default.bin' */
        @JsonProperty("kernel_name")
        private Object kernel_name;

        /** The RAM size, in MiB. */
        @JsonProperty("mem_size_mib")
        private Object mem_size_mib;

        /** How many vCPUs to allocate to this VM (and its children) */
        @JsonProperty("vcpu_count")
        private Object vcpu_count;

        public VmCreateVmConfig() {}

        public Object getFsSizeMib() { return fs_size_mib; }
        public void setFsSizeMib(Object fs_size_mib) { this.fs_size_mib = fs_size_mib; }

        public Object getImageName() { return image_name; }
        public void setImageName(Object image_name) { this.image_name = image_name; }

        public Object getKernelName() { return kernel_name; }
        public void setKernelName(Object kernel_name) { this.kernel_name = kernel_name; }

        public Object getMemSizeMib() { return mem_size_mib; }
        public void setMemSizeMib(Object mem_size_mib) { this.mem_size_mib = mem_size_mib; }

        public Object getVcpuCount() { return vcpu_count; }
        public void setVcpuCount(Object vcpu_count) { this.vcpu_count = vcpu_count; }

    }

    /**
     * Response body for DELETE /api/vm/{vm_id}
     */
    public static class VmDeleteResponse {
        @JsonProperty("vm_id")
        private String vm_id;

        public VmDeleteResponse() {}

        public String getVmId() { return vm_id; }
        public void setVmId(String vm_id) { this.vm_id = vm_id; }

    }

    /**
     * Response body for POST /api/v1/commit_tags
     */
    public static class CreateTagResponse {
        /** The commit ID this tag points to */
        @JsonProperty("commit_id")
        private String commit_id;

        /** The ID of the newly created tag */
        @JsonProperty("tag_id")
        private String tag_id;

        /** The name of the tag */
        @JsonProperty("tag_name")
        private String tag_name;

        public CreateTagResponse() {}

        public String getCommitId() { return commit_id; }
        public void setCommitId(String commit_id) { this.commit_id = commit_id; }

        public String getTagId() { return tag_id; }
        public void setTagId(String tag_id) { this.tag_id = tag_id; }

        public String getTagName() { return tag_name; }
        public void setTagName(String tag_name) { this.tag_name = tag_name; }

    }

    /**
     * Tag information within a repository context
     */
    public static class RepoTagInfo {
        /** The commit ID this tag currently points to */
        @JsonProperty("commit_id")
        private String commit_id;

        /** When the tag was created */
        @JsonProperty("created_at")
        private String created_at;

        /** Optional description */
        @JsonProperty("description")
        private Object description;

        /** Full reference in image_name:tag format */
        @JsonProperty("reference")
        private String reference;

        /** The tag's unique identifier */
        @JsonProperty("tag_id")
        private String tag_id;

        /** The tag name */
        @JsonProperty("tag_name")
        private String tag_name;

        /** When the tag was last updated */
        @JsonProperty("updated_at")
        private String updated_at;

        public RepoTagInfo() {}

        public String getCommitId() { return commit_id; }
        public void setCommitId(String commit_id) { this.commit_id = commit_id; }

        public String getCreatedAt() { return created_at; }
        public void setCreatedAt(String created_at) { this.created_at = created_at; }

        public Object getDescription() { return description; }
        public void setDescription(Object description) { this.description = description; }

        public String getReference() { return reference; }
        public void setReference(String reference) { this.reference = reference; }

        public String getTagId() { return tag_id; }
        public void setTagId(String tag_id) { this.tag_id = tag_id; }

        public String getTagName() { return tag_name; }
        public void setTagName(String tag_name) { this.tag_name = tag_name; }

        public String getUpdatedAt() { return updated_at; }
        public void setUpdatedAt(String updated_at) { this.updated_at = updated_at; }

    }

    /**
     * Response for exec log tail requests.
     */
    public static class VmExecLogResponse {
        /** Returned log entries. */
        @JsonProperty("entries")
        private List<VmExecLogEntry> entries;

        /** True when the end of file was reached. */
        @JsonProperty("eof")
        private Boolean eof;

        /** Next byte offset to continue from. */
        @JsonProperty("next_offset")
        private Long next_offset;

        public VmExecLogResponse() {}

        public List<VmExecLogEntry> getEntries() { return entries; }
        public void setEntries(List<VmExecLogEntry> entries) { this.entries = entries; }

        public Boolean getEof() { return eof; }
        public void setEof(Boolean eof) { this.eof = eof; }

        public Long getNextOffset() { return next_offset; }
        public void setNextOffset(Long next_offset) { this.next_offset = next_offset; }

    }

    /**
     * Response for GET /api/v1/vm/{vm_id}/metadata
     */
    public static class VmMetadataResponse {
        @JsonProperty("created_at")
        private String created_at;

        @JsonProperty("deleted_at")
        private Object deleted_at;

        @JsonProperty("grandparent_vm_id")
        private Object grandparent_vm_id;

        @JsonProperty("ip")
        private String ip;

        @JsonProperty("owner_id")
        private String owner_id;

        @JsonProperty("parent_commit_id")
        private Object parent_commit_id;

        @JsonProperty("state")
        private VmState state;

        @JsonProperty("vm_id")
        private String vm_id;

        public VmMetadataResponse() {}

        public String getCreatedAt() { return created_at; }
        public void setCreatedAt(String created_at) { this.created_at = created_at; }

        public Object getDeletedAt() { return deleted_at; }
        public void setDeletedAt(Object deleted_at) { this.deleted_at = deleted_at; }

        public Object getGrandparentVmId() { return grandparent_vm_id; }
        public void setGrandparentVmId(Object grandparent_vm_id) { this.grandparent_vm_id = grandparent_vm_id; }

        public String getIp() { return ip; }
        public void setIp(String ip) { this.ip = ip; }

        public String getOwnerId() { return owner_id; }
        public void setOwnerId(String owner_id) { this.owner_id = owner_id; }

        public Object getParentCommitId() { return parent_commit_id; }
        public void setParentCommitId(Object parent_commit_id) { this.parent_commit_id = parent_commit_id; }

        public VmState getState() { return state; }
        public void setState(VmState state) { this.state = state; }

        public String getVmId() { return vm_id; }
        public void setVmId(String vm_id) { this.vm_id = vm_id; }

    }

    /**
     * Request body for PATCH /api/vm/{vm_id}/disk
     */
    public static class VmResizeDiskRequest {
        /** The new disk size in MiB. Must be strictly greater than the current size. */
        @JsonProperty("fs_size_mib")
        private Integer fs_size_mib;

        public VmResizeDiskRequest() {}

        public Integer getFsSizeMib() { return fs_size_mib; }
        public void setFsSizeMib(Integer fs_size_mib) { this.fs_size_mib = fs_size_mib; }

    }

    /**
     * The response body for POST /api/vm/{vm_id}/commit
     */
    public static class VmCommitResponse {
        /** The UUID of the newly-created commit */
        @JsonProperty("commit_id")
        private String commit_id;

        public VmCommitResponse() {}

        public String getCommitId() { return commit_id; }
        public void setCommitId(String commit_id) { this.commit_id = commit_id; }

    }


    // ── Params types for operations with query parameters ───────────────

    /**
     * Query parameters for ResizeVmDiskParams.
     */
    public static class ResizeVmDiskParams {
        /** If true, return an error immediately if the VM is still booting. Default: false */
        public Boolean skip_wait_boot;

    }

    /**
     * Query parameters for CreateNewRootVmParams.
     */
    public static class CreateNewRootVmParams {
        /** If true, wait for the newly-created VM to finish booting before returning. Default: false. */
        public Boolean wait_boot;

    }

    /**
     * Query parameters for VmLogsParams.
     */
    public static class VmLogsParams {
        /** Byte offset into the log file (default: 0) */
        public Long offset;

        /** Maximum number of log entries to return */
        public Long max_entries;

        /** Filter by 'stdout' or 'stderr' */
        public String stream;

    }

    /**
     * Query parameters for BranchByRefParams.
     */
    public static class BranchByRefParams {
        /** Number of VMs to branch (optional; default 1) */
        public Long count;

    }

    /**
     * Query parameters for BranchByTagParams.
     */
    public static class BranchByTagParams {
        /** Number of VMs to branch (optional; default 1) */
        public Long count;

    }

    /**
     * Query parameters for BranchVmParams.
     */
    public static class BranchVmParams {
        /** If true, keep VM paused after commit. Only applicable when branching a VM ID. */
        public Boolean keep_paused;

        /** If true, immediately return an error if VM is booting instead of waiting. Only applicable when branching a VM ID. */
        public Boolean skip_wait_boot;

        /** Number of VMs to branch (optional; default 1) */
        public Long count;

    }

    /**
     * Query parameters for UpdateVmStateParams.
     */
    public static class UpdateVmStateParams {
        /** If true, error immediately if the VM is not finished booting. Defaults to false */
        public Boolean skip_wait_boot;

    }

    /**
     * Query parameters for DeleteVmParams.
     */
    public static class DeleteVmParams {
        /** If true, return an error immediately if the VM is still booting. Default: false */
        public Boolean skip_wait_boot;

    }

    /**
     * Query parameters for BranchByVmParams.
     */
    public static class BranchByVmParams {
        /** If true, keep VM paused after commit */
        public Boolean keep_paused;

        /** If true, immediately return an error if VM is booting instead of waiting */
        public Boolean skip_wait_boot;

        /** Number of VMs to branch (optional; default 1) */
        public Long count;

    }

    /**
     * Query parameters for CommitVmParams.
     */
    public static class CommitVmParams {
        /** If true, keep VM paused after commit */
        public Boolean keep_paused;

        /** If true, return an error immediately if the VM is still booting. Default: false */
        public Boolean skip_wait_boot;

    }

    /**
     * Query parameters for ListDomainsParams.
     */
    public static class ListDomainsParams {
        /** Filter by VM ID */
        public String vm_id;

    }

    /**
     * Query parameters for BranchByCommitParams.
     */
    public static class BranchByCommitParams {
        /** Number of VMs to branch (optional; default 1) */
        public Long count;

    }

}
